### ISSUE TITLE
Relevant Qualifications

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/apply#1015]
Currently, the Relevant Qualifications section is optional - This should be made mandatory for at least x1 entry

https://jac-apply-develop--pr1013-feature-1005-optiona-gli2a4qr.web.app/apply/sx5Vvkl80a93r1VqO5vt/relevant-qualifications

![Image](https://user-images.githubusercontent.com/97609636/240241165-fd43b33d-148b-4fb8-8916-9bfb2824822f.png)

**Comment by nickaddy** [comment]
@nickaddy to discuss with Matt to investigate options for candidates that do not meet the qualification criteria.
