### ISSUE TITLE
Application form improvements

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/apply#1040]
User story
As a candidate, I would like to be able to input my career history and experience including gaps in employment in a single form so that assessors can easily view my relevant career history.

Background from Roadmap
We have recently established a working group representative of a cross section of JAC staff/teams to look at whether improvements could be made to the application form, not least to better ensure accurate, comprehensive data is collected from candidates.

The proposed improvements are captured on [this Miro board](https://miro.com/app/board/uXjVM1RVfpA=/?userEmail=nick.addy@judicialappointments.digital&track=true&utm_source=notification&utm_medium=email&utm_campaign=add-to-board&utm_content=go-to-board)

![image.png](https://images.zenhubusercontent.com/64a540c0fc632dc95351b78a/b978c8ba-613f-4b53-a871-14ee444b953a)

**Comment by nickaddy** [comment]
Shared Norma's Miro board with Jeremy, who will share with Shan for wireframe build early next week. Wireframe should be run through UT ahead of actual build.

**Comment by JeremykJAC** [comment]
https://www.figma.com/file/5XatHx18Pabno2dGrgeYtS/%231040---Application-form-improvements?type=design&node-id=0-1&mode=design&t=wHLvlHcR1SgdC7n6-0

https://www.figma.com/proto/5XatHx18Pabno2dGrgeYtS/%231040---Application-form-improvements?page-id=0%3A1&type=design&node-id=4-3684&viewport=303%2C280%2C0.03&t=LPxEZihDJvYS8DBq-1&scaling=min-zoom&starting-point-node-id=4%3A3684&mode=design

**Comment by nickaddy** [comment]
Involve working group in UT

**Comment by nickaddy** [comment]
@JeremykJAC I've spoken with Matt re your calculation suggestion. Currently, we don't need to calculate the non-judicial work experience days (although that could be a feature for the future.) For the judicial roles, the candidates will enter the number of sitting days. We need to calculate the total number of days by totting up all the judicial sitting days and all the quasi-judicial sitting days that the candidates have input for each role in the judicial section.

If that total is less than the required number of sitting days specified, we would require a modal/smart field with a message:

As you have indicated you have less than X number of sitting days across all judicial and/or quasi-judicial appointments, please provide details of  how you have acquired the necessary skills for this role in some other significant way.

Following on, there would be a free text field for them to submit the evidence.

There is one amend:

The question "Is a legal qualification a requisite for appointment?" should be rephrased to "Was a legal qualification necessary for appointment to this role?"

Happy to chat through the above, otherwise, if it all makes sense, we can get cracking with developing a working prototype for testing :-)

**Comment by warrensearle** [comment]
@JeremykJAC to address the above changes and then create an additional mock-up so the two approaches can be reviewed by the working group

**Comment by JeremykJAC** [comment]
https://www.figma.com/proto/5XatHx18Pabno2dGrgeYtS/%231040---Application-form-improvements?page-id=0%3A1&type=design&node-id=4-3684&viewport=199%2C308%2C0.13&t=NiGFwt0GsOeMcBAq-1&scaling=min-zoom&starting-point-node-id=4%3A3684&mode=design

**Comment by JeremykJAC** [comment]
https://www.figma.com/proto/5XatHx18Pabno2dGrgeYtS/%231040---Application-form-improvements?page-id=0%3A1&type=design&node-id=4-3684&viewport=199%2C308%2C0.13&t=NiGFwt0GsOeMcBAq-1&scaling=min-zoom&starting-point-node-id=4%3A3684&mode=design

**Comment by warrensearle** [comment]
@JeremykJAC please can you share the link to the latest figma designs...'option 2' I believe. The above two links are the same and of an earlier iteration

**Comment by nickaddy** [comment]
[This ](https://www.figma.com/proto/5XatHx18Pabno2dGrgeYtS/%231040---Application-form-improvements?page-id=0%3A1&type=design&node-id=4-3684&viewport=199%2C308%2C0.13&t=NiGFwt0GsOeMcBAq-1&scaling=min-zoom&starting-point-node-id=4%3A3684)is the version that was demoed to the working group.

**Comment by nickaddy** [comment]
Matt's input on wording amends/additions below.

Meaning of Quasi-judicial:
Quasi-judicial refers to a role similar to that of a judge such as the chair of an equivalent body for which a legal qualification is required. An equivalent body is one of a quasi-judicial nature for which the powers and procedures should resemble those of a court of law and involve highly complex matters, requiring its members objectively to determine the facts and draw conclusions to reach a reasoned decision. Such decisions could result in the imposition of a penalty, and they are likely to affect the legal rights, duties or privileges of specific parties. Examples could include, but are not restricted to disciplinary tribunals and conduct hearings for professional standards bodies, the parole board, arbitration and chairs of statutory inquiries. 

Sitting days:
If you have been in post for a long time and have sat for more than 100 days, an approximate figure will suffice.

**Comment by warrensearle** [comment]
This looks great 👍

**Comment by JeremykJAC** [comment]
@warrensearle Here you go:

Version1 (original): https://www.figma.com/file/5XatHx18Pabno2dGrgeYtS/%231040---Application-form-improvements?type=design&node-id=191-1168&mode=design

Version2 (new): https://www.figma.com/file/5XatHx18Pabno2dGrgeYtS/%231040---Application-form-improvements?type=design&node-id=0-1&mode=design

**Comment by nickaddy** [comment]
@JeremykJAC @HalcyonJAC Matt is content with the text below for candidates not meeting the requisite minimum no. of sitting days:

As you have indicated you have fewer than xxx sitting days across all judicial and/or quasi-judicial appointments, please provide details of how you have acquired the necessary skills for this role in some other significant way.

**Comment by warrensearle** [comment]
@nickaddy to add some additional text changes
