### ISSUE TITLE
Qualifications Section Appears For Non Legal Exercises

### ISSUE THREAD

**Issue by drieJAC** [jac-uk/apply#1043]
@MattHowley @warrensearle Can we confirm whether non legal exercises should display a Qualifications section in Apply?
Currently in Admin a non-legal exercise does not display Qualifications in the Eligibility tab so presumably the section shouldn't appear in Apply.
It's worth also confirming if (for a Legal exercise) no qualifications are specified then should the Qualifications section appear in Apply?

Live application for non-legal exercise: https://apply.judicialappointments.digital/apply/u5KTezC7wpndyWgl0wZ7/relevant-qualifications

With a screenshot of it below:

<img width="1726" alt="Screenshot 2023-08-17 at 13 35 51" src="https://github.com/jac-uk/apply/assets/115651787/0ba4e235-66bf-46ae-a804-1c19e8788a55">

**Comment by MattHowley** [comment]
Hi @drieJAC - no, I've not come across (or at least don't recollect) a non-legal exercise for which qualifications are required - the criteria tends to be membership of a particular professional body or experience of a particular nature. If we are able to disable the qualifications section for non-legal exercises that would be grand.
