### ISSUE TITLE
Add Guidance Instructions

### ISSUE THREAD

**Issue by drieJAC** [jac-uk/apply#1044]
The updated requirements for this ticket, after discussions with Nick, are to add some text above the apply button to warn the users that clicking on 'Apply' means they are agreeing to some terms.

See original request below:

> Rob and Matt are a little concerned that we are overly policing candidates by preventing them from applying unless they tick to confirm they have read all the guidance. Would you be content with us just including text above the apply button instead of having a tick box and greying out the apply button. The text would read:
>  
> ‘By clicking the apply button you are agreeing that you have read all the information on the exercise information page and any guidance referred to’

**Comment by drieJAC** [comment]
@nickaddy Can I get a Welsh translation for the following text please?

By clicking the apply button you are agreeing that you have read all the information on the exercise information page and any guidance referred to.

**Comment by nickaddy** [comment]
Over to you @drieJAC 

Drwy glicio ar y botwm apply, rydych yn cytuno eich bod wedi darllen yr holl wybodaeth ar y dudalen ymarfer ac unrhyw ganllawiau y cyfeirir atynt.

**Comment by nickaddy** [comment]
Just to be clear, there is no need to remove the checkbox - it doesn't exist yet, that was one idea that was ruled out

**Comment by drieJAC** [comment]
Awaiting feedback from @nickaddy on exactly which page this goes on

**Comment by drieJAC** [comment]
Nick has confirmed that the page is in the screenshot below:

![Screenshot 2023-08-18 at 11 21 00](https://github.com/jac-uk/apply/assets/115651787/4af20b7e-ad7e-4734-a211-1199c6391552)

**Comment by nickaddy** [comment]
![image](https://github.com/jac-uk/apply/assets/138654969/dc7f2ca9-719b-4ebf-a312-74d86ece76b6)

@drieJAC shared the above screenshot

**Comment by nickaddy** [comment]
@drieJAC This has been approved by Meena Islam in Policy and, I believe, can be merged as it is purely a cosmetic change?
