### ISSUE TITLE
Capture Commissioner Conflicts

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/apply#1066]
**User Story** 
As an applicant, I would like to specify any commissioner conflicts so that this can be taken into account during my application.

**[Background]**
Currently, commissioner conflicts are captured on Google Forms, but the objective is to embed this functionality on the platform. Additionally, Judicial Office are keen that this information is captured in the early stages of application. 
Currently only Commissioner email addresses are captured in the database; we need to add their names too.
We would like to provide candidates with the opportunity to declare any pre-existing relationships they have with the JAC Commissioners so that this information can be taken into account when assessing their applications.

**Feature** 
This is a new section to be added under Additional Information.
We should present to the candidates a list of the commissioners names from the database with the option to select yes/no radio buttons for each one. 
By default all radio buttons should be deselected.
When 'yes' is selected, a free text box should appear under that commissioner, prompting the applicant to enter details of their relationship.

[Miro board here](https://miro.com/app/board/uXjVMhy_k0o=/?share_link_id=19922587091)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUVDQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--14e8afef69c37f3f853a30e276950f6a892d8764/image.png)

**MOSCOW**
Use this technique to prioritise all requirements .
[]Must have - Displays list of commissioners' NAMES (extracted from database) with yes/no radio buttons next to each
[]Must have - If yes selected next to a commissioner, a free text box appears underneath with message inviting candidates to specify pre-existing relationship. 
[]Must have - By default, no buttons are selected and the candidate receives an error message if they try to save and continue with any of the buttons unselected
**[]Should have - A button underneath the list that allows the applicant to 'Set all buttons to 'No' - the button could be titled 'I do not have a pre-existing relationship with any of the commissioners'**

**[Ticket Champion]**
Joanne Dixon

**Comment by nickaddy** [comment]
@warrensearle @tomlovesgithub Norma & I have created this ticket for the October sprint, can you please review/comment?

**Comment by drieJAC** [comment]
The work required will be to:

- Modify the way the commissioner data is stored and provide an endpoint in to fetch the commissioner names as a list (DP)
- Retrieve the commissioner names and display the form with the checkboxes and the textarea so the user can indicate any conflicts of interest
- Save the conflicts of interest data in the application (DP)
- Display the new section back to the applicant with the 'Done' label next to it (see MIRO)
