### ISSUE TITLE
Rename Additional Information section

### ISSUE THREAD

**Issue by NormaJAC** [jac-uk/apply#1068]
**User Story** 
As an applicant, I would like to see the "How did you hear about the vacancy?" so that I can answer the question "How did you hear about the vacancy?" during my application process.

**History/context**
Currently, we are revising the application form. There is a section named "Additional Information" which has a sub-page also named "Additional information". When an applicant clicks on the sub-page, it opens up a page: "How did you hear about the vacancy?" therefore we want the page title to reflect its content. **We want to change the sub-page name to "How did you hear about the vacancy?"**

**Please make any corresponding changes on the admin side as appropriate**

**Estimate**
XS

**Visuals**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBby9hIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--55cd5f4b47eec3faf926a0bb367d56732b846e02/image.png)

**Comment by warrensearle** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/apply/1068?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub
