### ISSUE TITLE
Working preferences questions

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/apply#1072]
See Admin: [Configure working preferences questions](/jac-uk/admin/issues/2154)

There are a number of configuration changes outlined in [Configure working preferences questions](/jac-uk/admin/issues/2154).

Here we need to ensure these changes are correctly rolled out to the application form.

In particular:

## Improvements to existing functionality

- [x] Working preferences questions should be mandatory (if configured)
- [x] Ranking. Should not be able to skip numbers - e.g. choosing two answers from five means user can choose 1st and 2nd choice, not 1st and 5th
- [x] There can now be multiple location questions (currently there is only one)
- [x] There can now be multiple jurisdiction questions (currently there is only one)

## Use Jurisdictions from Vacancy Information

- [x] Ensure that we display answers from Vacancy Information > Jurisdictions if the question is configured

## Allow linked questions

- [x] Ensure linked questions are only asked if the corresponding linked answer has been selected
- [ ] Improve the navigation / ensure we ask linked questions from another preference type (either combine the preference questions into one page OR ensure linked questions from another preference are asked on both preference pages) 

## Allow grouping of answers

- [x] Display answer groups and nested answers

## Review

- [x] Update the Review page to correctly display the candidate's selections

https://github.com/jac-uk/apply/assets/8524401/3d87a3cd-c129-4f51-8a8c-279cb918105e

---

See the following [visuals](https://www.figma.com/file/aqILfbMFEy51XDaFZpid8i/Ranked-answers-with-linked-questions?type=design&mode=design)

**Comment by warrensearle** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/apply/1072?planning-poker) with Zenhub @drieJAC

**Comment by tomlovesgithub** [comment]
Note to self

- sign into apply 
- find working prefs examples 708 develop
- review page
