### ISSUE TITLE
Online tests link on apply website error message

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/apply#1094]
Description
When I log in to Apply (Production) and click on Online Tests in the left navigation, I receive the error below. Even if I haven't participated in any tests, I should receive a blank page rather than an error.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnhNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--84e004c55adef14dda26715e5c3de40401da6062/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnBNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fdfdabcac34ebf9cc6230b8fe173ca5e68ecac5c/image.png)

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/apply/1094?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by warrensearle** [comment]
@nickaddy this has been resolved in the removal of QT code admin#1933

**Comment by nickaddy** [comment]
Has that code not been released yet, then?

**Comment by warrensearle** [comment]
> Has that code not been released yet, then?

Correct. We haven't released that yet as it is bundled up with the upgrade to Vue 3

We can fix this bug in the meantime and release as a hot fix. Though probably preferable to direct the effort into getting the next version of Apply released instead. In which case this ticket can be closed/deleted

**Comment by nickaddy** [comment]
@warrensearle Nobody else has mentioned it, so agree, it can wait for the full Apply release. I will close it as there does not appear to be a way of deleting.
