### ISSUE TITLE
Mandating fields on Apply

### ISSUE THREAD

**Issue by NormaJAC** [jac-uk/apply#1097]
**Background**
Create a ticket to mandate all appropriate fields under Work experience, Selection criteria, Eligibility and Character. 
https://app.zenhub.com/workspaces/discovery-650a9b85a29719001aab198a/issues/zh/3

**User Story** 
As a candidate when I want to provide my _Work experience, Selection criteria, Eligibility and Character_, I must answer all the mandatory questions on **Relevant experience, Post-qualification experience, Judicial experience, Gaps in employment, Statement of suitability, Statement of eligibility** and **Self assessment** before being able to move to the next section, it would help if the appropriate questions are made mandatory, so that I do not miss any required answers.

(Sections to be mandated are below)
**Relevant experience** > Job title and Organisation or business name > make the: _Start date_ mandatory

**Post-qualification experience** > Provide details of your career to date including any judicial appointments or quasi-judicial appointments > **make the**: _Law-related tasks in this role_ **mandatory**

**Judicial experience** > Are you a fee-paid or salaried judge? > **make the** _Have you sat for at least x days?_ **mandatory** > **make this**: _Have you sat for at least x days in one or all of these appointments?_ **mandatory**

**Gaps in employment** > dates and details of any gaps in employment you may have > **make the**: _Start date_ **mandatory** > **make the**: _Law-related tasks in this role_ **mandatory**

**Statement of suitability**> Explanation of legal experience >**make this**: _Do you meet this requirement?_ **mandatory**

**Statement of eligibility** > Explanation of legal experience > **make this**: _Do you meet this requirement?_ **mandatory**

**Self assessment**> Additional criteria > **make this**:  _Do you meet this requirement?_ **mandatory**

**Acceptance Criteria** 
Given that I am on the aforementioned sections, when I'm completing the mandatory questions, then I must answer every question before I am allowed to move to the next section.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUhSQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb3de280ddd7d04488f723d3120287d2507d58d7/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUxSQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c6868588336a1aa9b9fb4d83cffa5f2a6f3da576/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVRSQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b82ef5bace8e037f78cd413f5ce59bb5f36369a/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWJSQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--abf20bd85086a877fe0a02688d08b20d687684ee/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWZSQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--23b7a7cb282fe5bfe069acb7819c2f598781ceff/image.png)

**Comment by nickaddy** [comment]
@NormaJAC to provide details of which fields are to be mandated and which not

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/apply/1097?planning-poker) with Zenhub @tomlovesgithub @warrensearle @HalcyonJAC
