### ISSUE TITLE
Upgrade Apply Platform to use latest Firebase library 

### ISSUE THREAD

**Issue by Franceswog** [jac-uk/apply#1134]
Following the upgrade of Admin repo, we need to upgrade the other repos to the latest version.

Useful links

https://firebase.google.com/docs/web/modular-upgrade

[ ] [jac-kit] Upgrade Firebase SDK to latest stable version
[ ] [admin] Upgrade Firebase SDK to latest stable version
[ ] [jac-kit] Update all the import statements from firebase to firebase/compat
[ ] [admin] Update all the import statements from firebase to firebase/compat
[ ] Refactoring Authentication functions to modular APIs
[ ] Refactoring Firestore functions to modular APIs
[ ] Refatoring firestoreAction
[ ] Update Firestore Action in store/*.js files
[ ] Upgrade VuexFire to VueFire

**Comment by Franceswog** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/apply/1134?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by tomlovesgithub** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/apply/1134?planning-poker) with Zenhub @KoWeiJAC

**Comment by warrensearle** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/apply/1134?planning-poker) with Zenhub @KoWeiJAC
