### ISSUE TITLE
Align ethnicity fields with census categories used by JDF partners

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/apply#1136]
## Background
In order to align with the ethnicity fields in the [2021 census](https://www.ethnicity-facts-figures.service.gov.uk/style-guide/ethnic-groups/) and with other JDF partners, we need to add a `Roma` option to the White category and an `Arab `option to the Other category on the Equality and Diversity section of the JAC application form. 

## Feature(s)

- [x] Add a `Roma` option to the White category on the JAC application form
<img width="465" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTB4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--34bb0c1c62d8cbdb3f6aa059d52079e387b30d07/image.png" alt="image.png" />

- [x] Add an `Arab `option to the Other category on the JAC application form
<img width="238" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTh4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fd2516c3fcc0c2da47f12149046798504fe895de/image.png" alt="image.png" />

- [x] Create a separate section for `Prefer not to say` with just one radio button
<img width="280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0V4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--808d7084c5f92b9625a1a83840eaea15a11e6d7c/image.png" alt="image.png" />

- [ ]  Include the new fields for all exercises starting after 1 April so as to align with new financial year

## Acceptance Criteria

- [ ] **Scenario 1: Add Roma option to the White category on the JAC application form**
  - Under the White category, all candidates should see a new option "Roma" 

- [ ] **Scenario 2: Add Arab option to the Other category on the JAC application form**
  - Under the Other category, all candidates should see a new option "Arab" 

- [ ] **Scenario 3: Create a separate section for `Prefer not to say` with just one radio button**
  - Under a new 'Prefer not to say' category, all candidates should see a new option 'Prefer not to say'
 
- [ ] **Scenario 4: Include new fields for all exercises starting after 1 April**
  - From 1 April onwards, all candidates completing an application form should see the new fields for ethnicity aligned with the 2021 census categories and JDF partners
 
## Feature Champion
Sean Cuddihy

**Comment by nickaddy** [comment]
@warrensearle Will any changes to Diversity report page/download/other reports be required as a result of these changes?

**Comment by KoWeiJAC** [comment]
@nickaddy 
If the new global `Prefer not to say` section is selected, 
all the questions with `prefer not to say` option will be selected automatically, is it correct ?
I'm thinking when the new global `Prefer not to say` section is selected,
we can hide all the questions having `prefer not to say`, and set the answers to `prefer not to say` in the background.
Is this way workable ?

**Comment by nickaddy** [comment]
@KoWeiJAC Not quite. The `Prefer not to say` section is a separate response under the `What is your ethnic group?` question - it has no connection with the other questions.

**Comment by KoWeiJAC** [comment]
@nickaddy 
Thank you for the clarification.
