### ISSUE TITLE
Optional working preferences questions appear as mandatory on Apply

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/apply#1178]
## Describe the bug
It is now possible in Admin to configure working preferences questions as optional, however, on Apply, questions configured this way still appear to be mandatory.

## Expected behaviour
Questions marked as optional in Admin should not be mandatory on Apply.

## Screenshots

**Admin. Configuring working preferences**
_Note the first question is optional_

<img width="881" alt="image" src="https://github.com/jac-uk/apply/assets/8524401/f33f0a7c-1121-487e-a630-f76bc9ab0017">

---

**Apply. Answering working preferences**

_Note the 'Save and continue' button is disabled. It should not be as the form has sufficient data entered (the first question is optional)_

<img width="563" alt="image" src="https://github.com/jac-uk/apply/assets/8524401/be5bd197-c4c4-4e48-8a3f-36789e7ceee0">

## Additional context
The save button only becomes enabled when all questions have been answered. We need to ensure optional questions are excluded from this check.

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/apply/1178?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by drieJAC** [comment]
Do we need to preserve existing behaviour for version 1 Working Preferences questions?

**Comment by nickaddy** [comment]
@drieJAC I believe WP questions were mandatory for v1. As we haven't fully released v2, I'm not sure when or if there is a cut-off date for exercises using v1. It's possible there could be exercises in draft status that will be using v1, so I suppose, yes, we need to preserve existing behaviour for any exercises using v1.

**Comment by KoWeiJAC** [comment]
@nickaddy 
I checked the code, the location preferences in v1 seems to be all optional, I'm not sure if it is correct.
Is it ok that we can preserve this behaviour(all optional) in v1, or we can make it all mandatory  in v1?
