### ISSUE TITLE
Candidate ability to update email

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/apply#119]
1) Candidates need to be able to change their account email address. Suggest this appears at the top where it confirms what email they are signed in with saying 'update email' 

2) Needs to connect to firebase so that this updates with the new email and they then log in with that email from that point onwards.

**Comment by ClaireTroughtonJAC** [comment]
Candidate side needs a separate ticket for phase 2.  Higher estimate.  Candidate profile
Button for admin - some existing page. .
