### ISSUE TITLE
Mandate NINo field in Personal details section of Application form

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/apply#1204]
## Background
On a recent exercise, a large number of candidates submitted applications without populating the NINo field. The NINo field was also blank in their account so was not copied across. It was agreed at the Ops management meeting on 25 July to make this field mandatory at application level.

## User Story
As an Admin, I would like to mandate the NINo field on the application form so that I have all the information necessary to check for duplicate applications.

## Feature(s) Description
- [x] Mandate completion of the NINo field in the personal details section of the application form
- [x] Remove the `(optional)` text next to the NINo field in the personal details section of the application form

<img width="446" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTBOQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0af6cd415df76fb5baaff2acc70123fbd35dd6f1/image.png" alt="image.png" />

## Acceptance Criteria 
It's done when the NINo field in the application form is mandatory and the (optional) text has been removed from that page.

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Specify for users what is being tested (but not how to test it.)

## Feature Champion
Nick

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/apply/1204?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by HalcyonJAC** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/apply/1204?planning-poker) with Zenhub @KoWeiJAC
