### ISSUE TITLE
Update character section of the application form

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/apply#1209]
## Background
A review of the Good Character Guidance has recently taken place, the resulting impact is that there will be amendments required to some of the questions asked of candidates in the character section of the application form to align with the changes. **The changes should apply only to exercises opening on or after 15 October 2024**, i.e. historic and current applications prior to that date should use the existing character questions. The deadline for changes to the character section to be tested and live

A companion tickets for [application view/edit](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/admin/2551) has also been created.

## User Story
As JAC, I would like the Character section of the Application form to be updated so that it is in line with the changes agreed by the board.

## Feature(s) Description
- [x] Changes to copy as per the [document attached](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1M4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4429012590020540647844f8e8bd5ab193bd29ae/Amendments%20requested%20to%20Character%20questions.docx)
- [x] In Admin, specify the character guidance options according to when the exercise was launched:
- For exercises launched, i.e. Open for applications date is, on or after 15/10/24, the 2024 guidance is presented
- For exercises launched, i.e. Open for applications date was, before 15/10/24, the 2020 guidance is presented
<img width="944" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG5aQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ba764035d059303fb583ef1bc009ecb67a63c77/image.png" alt="image.png" />

- [x] The content of the tickboxes appears in the SCC Annex download and on screen according to which guidance is relevant as described above
<img width="666" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1RTQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--71391e2226711c5633521a4adeea622d0a4f28db/image.png" alt="image.png" />
- [x] The Welsh translation of the Character questions is updated once supplied 

## Acceptance Criteria 
It's done when: 
- All exercises launching on or after 15/10/24 feature the updated Character questions on Apply
- All prior exercises feature the current Character questions
- Historic (completed) applications on Apply conform with the above
- Welsh translation is also updated

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Test the new questions.

## Feature Champion
Joanne Dixon

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/apply/1209?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by nickaddy** [comment]
@drieJAC I have changed the request here following your suggestion - much less hassle that way. Thanks for the suggestion!

**Comment by HalcyonJAC** [comment]
@nickaddy Should we also update the Welsh translation?

**Comment by nickaddy** [comment]
@HalcyonJAC I've just submitted the text for Welsh translation; it usually takes a few days to come back. I'm going to add this as a task on the ticket - pls feel free to re-estimate accordingly.

**Comment by nickaddy** [comment]
@HalcyonJAC I have shared with Joanne Dixon (Secretariat and customer) for feedback.
