### ISSUE TITLE
Update link on equality and diversity survey where it asks about PAJE in application to MOJ link and not JAC providing diversity page.

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/apply#121]
Replace JAC link with: https://www.judiciary.uk/about-the-judiciary/who-are-the-judiciary/diversity/pre-application-judicial-education-programme-paje/

Exact question on Equality and Diversity 'have you taken part in the Pre-application judicial education (PAJE)? 

![PAJE2](https://user-images.githubusercontent.com/27224574/76841094-34191780-6830-11ea-8463-796bdffc8da2.png)

**Comment by ClaireTroughtonJAC** [comment]
Screenshot now added.
