### ISSUE TITLE
Single email address on Apply for candidates

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/apply#1212]
## Background
On Apply, there are currently multiple locations where candidates can update their email addresses: in their profile, and in each new application they make. Current behaviour is that when a user starts a new application, the email address field prepopulates with the email address stored in their profile, however it can be edited. If the candidate edits their email address in their application, once the application is submitted, their email address is also updated in their profile and the candidate is asked to log out because their email address has changed. The proposed solution is to make the email address **read only** in the application form. 

Additionally, DOB and NINo fields should become **read only**.

This should be released at a time when there are no open exercises so that there are no complications with open applications.

## User Story
As JAC, I would like candidates to have a single current contact email address to avoid confusion when logging in to the platform/being contacted.

## Feature(s) Description
- [ ] When a candidate initiates a new application, the email address in the Personal details section is pre-populated from their profile (current behaviour) but is read-only, i.e. non-editable. in the application form
- [ ]  As above for DOB - editable only in candidate profile and read-only on application form
- [ ] As above for NINo - editable only in candidate profile and read-only on application form
- [ ] Add the following text next to the email, DOB and NINo fields in the application form: To edit this field, please visit your candidate profile.

## Acceptance Criteria 
It's done when: 
- [ ] candidates can no longer edit their email address within an application
- [ ] candidates can no longer edit their DOB within an application
- [ ] candidates can no longer edit their NINo within an application
- [ ] after a candidate updates their email address, DOB or NINo in their profile, it is automatically updated in any live applications

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
- Log in to Apply
- Start a new application
- Try to edit your email address in the personal details section of the application form
- Try to edit your DOB in the personal details section of the application form
- Try to edit your NINo in the personal details section of the application form

## Feature Champion
Nick

**Comment by drieJAC** [comment]
May be worth having a link to their candidate profile

**Comment by drieJAC** [comment]
After chatting to @nickaddy we decided the following regarding the fields mentioned above:

If the field **isnt** filled in then it should be editable in the application form
If the **is** filled in then it shouldnt be editable in the application form and should appear as text only, as opposed to a text input, with a link next to it to edit it in the candidate profile
