### ISSUE TITLE
Relevant Qualifications page:  If select "Barrister" change question

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/apply#122]
If the candidate applying for a Legal or Leadership role selects "Barrister" we need to change the question that appears "When did you qualify?" 
to 
"When did you complete pupillage?"  

We need to add a radio button for "I did not complete pupillage".  

If they select this radio button the following text should appear:  
 'please email the JAC with information about this'  

If possible please can the email in the be hyperlinked using the team mailbox email address.

**Comment by Rebecca-mcknight1991** [comment]
@Rebecca-mcknight1991 check process with teams.

**Comment by YaaL** [comment]
Hey @Rebecca-mcknight1991, @tomlovesgithub is going to do this.
Could you please confirm we still want the "please email JAC" part - or maybe a "Details" text field where candidate explains and then the team can email them?
