### ISSUE TITLE
Change wording of password reset link

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/apply#1227]
## Background
Now that we are going to be verifying email address changes with a limited validity link, it makes sense that we limit the validity of the password reset link for consistency and good practice. Also the wording of the auto-response should be updated.

## Feature(s) Description

- [x] Change the wording of the password reset email as follows:

Dear Candidate,

You recently requested to reset your password for your Judicial Appointments Commission (JAC) account. Click the link below to reset it. This password reset is only valid for the next 24 hours.

INSERT LINK HERE

If you did not request a password reset, please ignore this email. If you are having trouble clicking on the link above, copy and paste it into the address bar of your web browser and press return.

Thank you,
Judicial Appointments Commission

## Acceptance Criteria 

- [ ] Autoresponse content is updated as above

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Specify for users what is being tested (but not how to test it.)

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/apply/1227?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by warrensearle** [comment]
I'm not entirely sure we can change how long it takes for one of the email links (verify email / password reset) to expire. I think this is still firebase controlled and unpublished as it's 'subject to change' [see here](https://github.com/firebase/firebase-js-sdk/issues/1884)

**Comment by nickaddy** [comment]
@warrensearle Hmmm, that's a bit weird as it seems fairly standard to limit validity. Do we know what the default setting is, at least?

**Comment by nickaddy** [comment]
I have removed changing the validity from this ticket as it seems that is not an option in Firebase.

**Comment by HalcyonJAC** [comment]
**Note:** The template for the password reset has been updated on Develop.

<img width="818" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1lpQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e36ebcd1e4654536c130ad41479319687435191/image.png" alt="image.png" />

**Comment by nickaddy** [comment]
@HalcyonJAC Fine. Can you pls confirm and amend the validity in the email - it sounds from Warren's comment that the link may only be valid for 1 hour? Thx

**Comment by HalcyonJAC** [comment]
@nickaddy I have updated the validity to 1 hour in the email. Could you check it, please?

**Comment by nickaddy** [comment]
Looks good, @HalcyonJAC, thanks.

**Comment by HalcyonJAC** [comment]
@nickaddy Should I apply the changes to Staging & Production?

**Comment by nickaddy** [comment]
@HalcyonJAC Yes pls.

**Comment by HalcyonJAC** [comment]
The password reset template is updated on all environments:
- [Develop](https://console.firebase.google.com/project/digital-platform-develop/authentication/emails)
- [Staging](https://console.firebase.google.com/project/digital-platform-staging/authentication/emails)
- [Production](https://console.firebase.google.com/project/platform-production-9207d/authentication/emails)
