### ISSUE TITLE
Changes to applications list on Apply

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/apply#1233]
## Background
Minor changes to the way applications are displayed on Apply.

<img width="1041" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBellaQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a44cb01601b79dbf04075361d1e47717a0519137/image.png" alt="image.png" />

## User Story
As a candidate I would like to be able to see my historic applications so that I can use the content for new applications.

## Feature(s) Description

- [ ] Display the View draft application button even when the exercise has been archived and unpublished 
~~- [ ] Remove the View advert button when the exercise is archived~~

## Acceptance Criteria 
It's done when:
- [ ]  candidates are able to view historic applications irrespective of the exercise state

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Internal testing only

## Feature Champion
Nick

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/apply/1233?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by warrensearle** [comment]
Currently we need the advert (`vacancy` document) in order to display the application it informs the UI what elements should be included in the application (which application parts; which shortlisting content)

**Comment by nickaddy** [comment]
@warrensearle Noted. Ticket amended accordingly.

**Comment by HalcyonJAC** [comment]
**Note:**
- A vacancy document is required to display the candidate’s application on Apply.
- When an exercise is archived, the exercise will be unpublished.
- When an exercise is unpublish, the vacancy document will be deleted which makes candidates not able to view their application

**Possible Solution**:
Don't unpublish archived exercises so candidates are still able to view their applications.

**Comment by nickaddy** [comment]
@HalcyonJAC 'When an exercise is archived, the exercise will be unpublished' - this logic is correct and we should not change it. Neither should, I believe, archived exercises appear on Apply. If we are able to keep vacancy documents in the Vacancies collection to enable candidate viewing of historic applications, without any other repercussions, then let's do that.
