### ISSUE TITLE
Vacancy notifications

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/apply#138]
![image](https://user-images.githubusercontent.com/56963348/72825016-31ee6e80-3c6e-11ea-9821-f6b55c861264.png)

https://apply.judicialappointments.digital/vacancies 

Add a "Sign up" link to notify candidate about upcoming vacancies.
Use Notify.

**Comment by crablab** [comment]
@YaaL I'm going to suggest a new collection for this subscription. We'll need some admin changes too in the form. 

What do you think? This should probably be an epic with a number of tickets. Just spitballing we have:
- Apply: Handle external link or internal subscription for "Sign up for alert" 
- Apply: On click internal subscription registers user for subscription to that exercise (email confirmation?) 
- Apply (optional): view and manage your subscriptions 
- Admin: Supply external link or create internal subscription 
- Admin: View and remove subscribed candidates 
- Admin: Manually trigger update email (until we've worked out what the auto triggers are) 
+ associated Digital Platform functions. 

Do you think this is a sensible way to go? If so, I'll convert this to an epic and start ticketing it up.

**Comment by ClaireTroughtonJAC** [comment]
@crablab Thanks for this.  Right now the sign up links are created in a mailchimp account and all our alerts before the exercise is launched are sent to those who sign up there.  

The programme office is responsible for creating these alerts and we have over 3000 people registered with this service.  

I would love to move this to the platform and this functionality seems to more than fit the bill but there needs to be a communication to all those subscribers that we will be shutting this service down first.  

Given we are currently communicating about the old system this switch over is some ways off.  I would be grateful if you could create the tickets but this will have to go back on the backlog for now.

**Comment by crablab** [comment]
Thanks @ClaireTroughtonJAC - that is really useful. 

I'll create some tickets around this now, and convert it to an epic. 

We could definitely build this on the platform and start migrating new exercises to it, but I guess this probably isn't a priority right now.
