### ISSUE TITLE
Iterate on Back link component.

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/apply#140]
Currently the Back link component behaves exactly the same as clicking back on the browser. 

We need the Back link component to behave in relation to the structure of the app. 

For example, if a user clicks a link from the task list, the will navigate to a form page with a Back link present that will take them back to the task list page.

**Comment by ClaireTroughtonJAC** [comment]
@warrensearle Is this to do with the navigation that Enor is looking at?  Can we close this issue?

**Comment by warrensearle** [comment]
This is a valid suggestion so don't think we should close it.
