### ISSUE TITLE
Add confirmation page

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/apply#142]
When Candidate hits the "Send Application" button on the Review page:
~~- Confirmation page will show application reference number~~
~~- application.status will change from "draft" to "applied"~~
~~- Candidate cannot change the information on their application anymore~~
- Send email notification to Candidate that they've submitted their Application
- Run Post Qualification Experience checks to see if the Application needs to be flagged for not passing certain checks

Claire - I confirm that they cannot change information in the application after their application is submitted.

**Comment by warrensearle** [comment]
The remaining tasks listed in this issue are covered by admin#250 therefore closing this issue
