### ISSUE TITLE
New page:  Interview location preferences

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/apply#196]
**Is your feature request related to a problem? Please describe.**
Once the new interview location page is created on admin we need a page similar to the working preferences page for the candidate to complete.

**Describe the solution you'd like**
If the "interview locations" are selected in admin this new page must display after "Working preferences" on the apply for a role page.  It should display any bespoke questions at the top and then the preference option (i.e Single, Multiple, Ranked)

**Additional context**
This corresponds to ticket admin#271

**Comment by ClaireTroughtonJAC** [comment]
@warrensearle I have update the other tickets with more requirements.

**Comment by Rebecca-mcknight1991** [comment]
@ClaireTroughtonJAC potentially not needed. To discuss.

**Comment by KateMJAC** [comment]
No longer needed, due to remote interviews and #271 being a repeat, with more detail.
