### ISSUE TITLE
Review page issue:  Misleading label on candidate side

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/apply#226]
**Describe the bug**
When the candidate is asked "do you hold, or have you ever held in the past, a fee-paid judicial role" on the review page the response shows as "true or false"   this is confusing candidates when reviewing their applications.  

DBS2020: for the candidate side of the new digital platform the question of: Do you hold, or have you ever held in the past, a fee-paid judicial role? Answer is true/false but on the admin side we see yes/no and 

Participated in a Judicial Workshadowing Scheme
No
 
• Participated in Pre-application judicial education
No the candidate was also not able to change the above to Yes

**To Reproduce**
1. Go to Equality and diversity page 
2. Select a category under this question Do you hold, or have you ever held in the past, a fee-paid judicial role? 
3. Complete the application and review application
4. Under Equality and Diversity review section you will see "true or false"

**Expected behavior**
The review page should say yes or no. 

**Additional context**

**Comment by YaaL** [comment]
Looks like it's a more generic problem than just these two questions.

**Comment by ClaireTroughtonJAC** [comment]
@YaaL I have reviewed this bugfix and it is nearly complete.  

This part is complete
• Participated in Pre-application judicial education it now shows Yes or No.  

This part is NOT complete
Do you hold, or have you ever held in the past, a fee-paid judicial role? Answer is still true/false instead or No. Its says false.  However if the candidate has selected an option ie Fee-Paid Court judge this is now displaying.  
<img width="752" alt="Screenshot 2020-03-23 at 15 51 44" src="https://user-images.githubusercontent.com/27224574/77335578-43133480-6d1e-11ea-907c-4fba10436d3d.png">
<img width="952" alt="Screenshot 2020-03-23 at 15 51 59" src="https://user-images.githubusercontent.com/27224574/77335581-44446180-6d1e-11ea-8bcf-4b22c6ef19dc.png">

**Comment by YaaL** [comment]
@ClaireTroughtonJAC This should work as expected now.
