### ISSUE TITLE
Review Page: Unecessary questions displaying on Non-Legal review application page

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/apply#227]
**Is your feature request related to a problem? Please describe.**
On a Non-legal exercise the following questions have been removed from the Equality and Diversity Page.

Have you participated in a Judicial Workshadowing Scheme question 
Have you participated in Pre-application judicial education questions 

They are incorrectly still displaying on the Review application page and it is confusing candidates.

**Describe the solution you'd like**
When the exercise is a Non-legal type these questions should not be visible on the review page.

**Comment by warrensearle** [comment]
The above two questions have now been hidden for non-legal. 
In addition the "Current legal role" question has been hidden (as this is also hidden on the Equality & Diversity page).
