### ISSUE TITLE
Missing candidate's documents

### ISSUE THREAD

**Issue by YaaL** [jac-uk/apply#237]
**Describe the bug**
Documents uploaded by candidates (CV, Self Assessment, ...) sometimes can't be downloaded in admin.

After investigation, it became clear that the root of this problem is in apply - in case of issues with file upload (possibly bad network connection?) we update the application document with a reference to file without checking if the file actually was successfully uploaded.

**To Reproduce**
Candidate: unknown
Simulation: delete file from storage without editing the application in firestore.
Admin will generate a link to file that doesn't exist.

**Expected behavior**
We should verify file was uploaded before allowing saving the application.

**Comment by warrensearle** [comment]
Hey @YaaL can we improve the way we are collecting the file extension. Right now the following will break the upload:
1. Files with full stop in the title e.g. `my-cv.2020.pdf`
2. Files without extension name e.g. `my-cv`
