### ISSUE TITLE
The spelling of disciplinary needs to be correct on the Character page

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/apply#250]
@Rebecca-mcknight1991 commented on [Sun Mar 01 2020](https://github.com/jac-uk/admin/issues/309)

**Describe the bug**
From the team: 'I know this is a very small thing - I just wanted to check that we had used the correct spelling of Disciplinary'.

It is currently Diciplinary - the C should be an S. 

**Expected behavior**
Should be 'Disciplinary

**Screenshots**
image.png 
image.png

**Additional context**

---

@YaaL commented on [Wed Mar 11 2020](https://github.com/jac-uk/admin/issues/309#issuecomment-597675298)

@warrensearle we have this typo all over the place!

---

@YaaL commented on [Wed Mar 11 2020](https://github.com/jac-uk/admin/issues/309#issuecomment-597678783)

@Rebecca-mcknight1991 BTW shouldn't this issue live in apply?

---

@warrensearle commented on [Wed Mar 11 2020](https://github.com/jac-uk/admin/issues/309#issuecomment-597684885)

@YaaL oh dear I can see that, even in variable names!
Let's address the low impact changes as part of this ticket and create a log / seperate ticket for any variable name changes. Other issues will lead to variable name changes, so I think it makes sense to approach them in one batch.

**Comment by warrensearle** [comment]
@YaaL have created this ticket to document database variable names we should change digital-platform#248.

**Comment by YaaL** [comment]
@ClaireTroughtonJAC this displays correctly in apply.
