### ISSUE TITLE
Ethnic group appearing as UK on candidate summary of application 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/apply#258]
**Describe the bug**
When teams download the diversity report the ethnicity says UK where a candidate has not answered the question rather than remaining blank or indicating the question was not answered. 

**To Reproduce**
1. Go to: https://apply-staging.judicialappointments.digital
2. Edit profile to leave Ethnic profile blank on equality and diversity
3. Make an application
4. Go to: https://apply-staging.judicialappointments.digital
5. View your application
6. Go to Equality and Diversity
7. It will say 'Ethnic group	UK'

**Expected behavior**
The team would either expect the candidate to see 'Prefer not to say'

**Screenshots**
![Screenshot 2020-02-20 at 14.54.11.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/a51793cd-667a-491c-ac3d-f9518c5ecf39)

**Desktop (please complete the following information):**
 - OS X 10.14.6
 - Chrome
 - Version 79

**Additional context**

**Comment by tomlovesgithub** [comment]
cannot reproduce this locally has it since been fixed?
