### ISSUE TITLE
Remove two duplicate exercises from the database

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/apply#263]
**Describe the bug**
Several exercises have duplicate headings on the vacancies page.  

**To Reproduce**
1. Go to vacancy page 
2. In open vacancies see screenshots of the duplicates
3. Scroll down to either "open vacancies" or 'future applications'
4. See duplicate titles

**Expected behavior**
Remove the any exercise with "find out more" link below it in either "Open vacancies" or "Future applications"

**Screenshots**
![Duplicate 2.png](https://images.zenhubusercontent.com/5e3c2b35e9bf7c0ea1c2859a/f72996b7-9433-42dc-8d7f-51e9c245c4ed)
![Correct.png](https://images.zenhubusercontent.com/5e3c2b35e9bf7c0ea1c2859a/eb446d74-8f59-4ad1-9473-57d812e5138e)
<img width="900" alt="Screenshot 2020-03-24 at 17 52 59" src="https://user-images.githubusercontent.com/27224574/77460261-c3a66380-6df8-11ea-9a28-adfdef4df6b9.png">
<img width="930" alt="Screenshot 2020-03-24 at 17 53 14" src="https://user-images.githubusercontent.com/27224574/77460265-c43efa00-6df8-11ea-96bc-acc923104782.png">
<img width="735" alt="Screenshot 2020-03-24 at 17 53 44" src="https://user-images.githubusercontent.com/27224574/77460266-c43efa00-6df8-11ea-905d-a20a111527dc.png">

**Additional context**

**Comment by YaaL** [comment]
This has been done.
