### ISSUE TITLE
SPIKE: use MoJ design system

### ISSUE THREAD

**Issue by YaaL** [jac-uk/apply#270]
[MoJ Design System](https://moj-design-system.herokuapp.com/) - we're already ~using~ following elements of it:

- [Add another](https://moj-design-system.herokuapp.com/components/add-another)
- [Task list](https://moj-design-system.herokuapp.com/components/task-list)
- [Timeline](https://moj-design-system.herokuapp.com/components/timeline)
- ...

It contains other elements that would be useful for our project too so it starts to make sense to add it permanently.

**Comment by YaaL** [comment]
Just found this: https://github.com/ministryofjustice/moj-design-system-backlog/issues/53

**Comment by ClaireTroughtonJAC** [comment]
@YaaL Please can you confirm that this issue is now superceded because of the UX work?  Can I close the issue?

**Comment by warrensearle** [comment]
Hey @ClaireTroughtonJAC lets leave this ticket open for now.
We are deciding whether to use MoJ Design System and will close this ticket once we've made that decision and created any follow on tickets.
