### ISSUE TITLE
Vacancy overview not showing until shortlisting methods defined

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/apply#272]
**Actual**
The vacancy overview page is displaying as an empty white screen when shortlisting methods are yet to be defined.

**Expected**
Vacancy overview page should display any data that has been provided. 
The only data that is required in order to display the overview page is "About The Role"

**Comment by ClaireTroughtonJAC** [comment]
@warrensearle I am still getting blank screens for all open exercises on staging.

**Comment by warrensearle** [comment]
Oh dear! This is fixed now. 
The page was breaking because it was expecting there to be exercise downloads in related content.
