### ISSUE TITLE
Get vacancy open and close time from database

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/apply#277]
Vacancy open and close time is now available in the database. We can therefore remove all hard-coded times from our code and simply use the date/time coming from the following fields:
`applicationOpenDate`
`applicationCloseDate`

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle this still a thangggg?

**Comment by warrensearle** [comment]
Yes this is still needed but is not essential so could be pushed back to 2021
