### ISSUE TITLE
Non-numerics allowed in IA phone number box

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/apply#290]
**Describe the bug**
As a candidate I can enter non-numerics in phone number. 

**To Reproduce**
1. Go to exercise
2. Click to apply 
3. Scroll down to Independent Assessments
4. Type non-numerics in 
5. Save and continue
6. Will allow non numbers

**Expected behavior**
To only allow numbers and to put in help text asking them to put 0 if they do not know the phone number.

**Comment by ClaireTroughtonJAC** [comment]
@ClaireTroughtonJAC @Rebecca-mcknight1991 Draft some help text for this.

**Comment by KateMJAC** [comment]
Just tested and doesn't allow non-numbers on saving.
