### ISSUE TITLE
Candidate fills in and submits consent form

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/apply#299]
**Is your feature request related to a problem? Please describe.**
As a candidate I need to be able to provide information and consent for character checks. 

**Describe the solution you'd like**
The candidate to be taken through the pages on the prototype for professional body info, HMRC info and declaration of consent. https://jac-apply-prototype.herokuapp.com/current/submit-consent-form/

**Consent statement**

![Screenshot 2020-05-29 at 14.55.33.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/795c8bf3-de31-4c4b-aeb0-bfcd68b4949e)

**Personal info**

![Screenshot 2020-05-29 at 14.55.40.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/c3c872cc-febf-4583-bc83-31db329004e0)

![Screenshot 2020-05-29 at 14.55.45.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/d02ce154-4c56-41a1-8bc4-031fa739d641)

![Screenshot 2020-05-29 at 14.55.50.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/9100472f-ff61-49ce-9c86-e1fc9cacaa27)

**Professional bodies**

![Screenshot 2020-05-29 at 14.55.55.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/31ed190f-c82a-417f-840c-942b2fceeea2)

![Screenshot 2020-06-01 at 11.44.13.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/f52bcf29-bf2a-4f8d-bf66-e3aa58bb4e1e)

![Screenshot 2020-06-01 at 11.44.24.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/91c83ae8-f265-40c0-9c0f-0cd242e2e830)

![Screenshot 2020-06-01 at 11.44.19.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/275342f9-fba9-42b3-af5f-ad4d169c0189)

![Screenshot 2020-06-01 at 11.44.29.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/e3749fc9-32dc-4e4d-9321-8c25398225be)

**HMRC**

![Screenshot 2020-05-29 at 14.55.58.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/3eb074e8-afe0-4d0d-8e9b-4066759fe821)

![Screenshot 2020-06-01 at 11.44.34.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/2031e497-0e61-4301-a07f-452f94ab8590)

**Summary page**

![Screenshot 2020-05-29 at 14.56.05.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/d98f13f9-c690-49a2-97f7-9a953eccf92a)

**Declaration** 

![Screenshot 2020-06-01 at 11.46.13.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/5f34885c-af1a-4a70-8079-7620324b5d1a)

![Screenshot 2020-06-01 at 11.46.22.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/0722d3e5-5776-45fe-bcf5-c808e3783363)

**Submission** 

![Screenshot 2020-06-01 at 11.46.29.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/d0f8bfb8-52f6-4ada-94f3-405d0b76c07a)

**Comment by crablab** [comment]
Reviewed :)

**Comment by andrew-isaac** [comment]
@HalcyonJAC  - We will need to provide updated wording for these pages - we are in the process of getting this signed off
