### ISSUE TITLE
Character checks in candidate account

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/apply#300]
**Is your feature request related to a problem? Please describe.**
As a candidate I want to be able to see the information I declared in the consent form in my account. 

**Describe the solution you'd like**
A link to the consent form on the candidate account.

@ClaireTroughtonJAC where should this go? Under Applications - good character consent.

**Comment by ClaireTroughtonJAC** [comment]
Hi @YaaL I am content that I can see the view sent consent form
