### ISSUE TITLE
Post qualification experience start date not showing on review for present roles 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/apply#301]
**Describe the bug**
When someone is currently in a role and so leaves the end date blank the dates do not appear on the review page. 

**To Reproduce**
1. Go to 00026 on live
2. Click on apply and fill in all details, put no end date on post qualification experience
3. Scroll down to review application

![Screenshot 2020-06-08 at 09.25.04.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/67c5e9c7-9081-4916-975a-ab146031dd67)

**Expected behavior**
The start date should show 

https://admin.judicialappointments.digital/exercises/p4pcU9EQhvPf2AMF8hxZ/

**Comment by warrensearle** [comment]
This should have been fixed in release 1.5.0 (released today). 
@Rebecca-mcknight1991 please can you double-check.
