### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by lloback** [jac-uk/apply#316]
**Describe the bug**
Update de dependencies

**Expected behavior**
After the update everything should work, so a monitoring of the app should be held.

**Comment by HalcyonJAC** [comment]
I have completed this ticket as part of the following tickets

**Comment by HalcyonJAC** [comment]
I have done the following:

- Installed Snyk on all GitHub repos 
- While doing the Vulnerability - npm audit ticket (for the apply portal) I upgraded as many packages as possible, without breaking stuff.

**Comment by HalcyonJAC** [comment]
I spoke to @warrensearle and we came up with the following plan:

- [x] Upgrade existing dependancies (where upgrades do not incur breaking changes)
- [x] Setup Snyk (to get an initial list of vulnarabilities)
- [ ] Setup Dependabot in GitHub (to get alerts about dependancy upgrades in future)
- [ ] Setup GitHub Code Scanning (to scan the JAC's own code for vulnerabilities)
- [ ] Disable Snyk (once all of the above has been done)
