### ISSUE TITLE
Vacancy details. 'Duplicate keys detected' error

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/apply#324]
On the following vacancy details page there is a 'duplicate keys detected' error:
http://localhost:8181/vacancy/ciss22KVrFkstlG7G2Nw/

Also see following screengrab:
![Screenshot 2020-07-10 at 12.52.01.png](https://images.zenhubusercontent.com/5e412648a39708a606c962c9/88fa8a2a-7de8-400c-b2ba-ef1f66e1559a)

**Comment by andrew-isaac** [comment]
@warrensearle - Can this be closed as the ticket has been open since 2020

**Comment by warrensearle** [comment]
Yes I think that's best! 
Closed
