### ISSUE TITLE
Missing key prevents google sign in on apply-staging

### ISSUE THREAD

**Issue by tomlovesgithub** [jac-uk/apply#379]
**Describe the bug**
Google sign in broken

**To Reproduce**
- log out of staging
- attempt to log back in
- view error

**Comment by warrensearle** [comment]
This has been fixed now.
We made some changes to our staging Firebase API key as well as CircleCI, so kicking off a fresh build of staging has resolved it.
- [ ] Admin staging has also been re-built.
- [ ] Assessments staging has also been re-built.

**Comment by tomlovesgithub** [comment]
Like magic!
