### ISSUE TITLE
QT Browser testing

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/apply#395]
We need to test our UI on more platforms & browsers, perhaps using BrowserStack or similar to identify any incompatibilities.

Browser Compatibility: Ensuring all major browsers: Google Chrome, Mozilla Firefox and Safari work on the platform and the live QT. Microsoft Edge is the only browser which seems to work fine with no issues.

Device Compatibility: Ensuring the platform works effectively with Apple devices: Mac Book Pro and Ipads as well.

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle what is this? remind me.

**Comment by warrensearle** [comment]
@Rebecca-mcknight1991 this is to check that QTs works on all browsers we support.

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle I thought so. I think this may need to shift to 2021. It was not a major issue within the test and we already know IE can be a problem. Definitely something we should make sure is captured as something to do as QTs get perfected though.
