### ISSUE TITLE
Equality and Diversity Page

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/apply#400]
As the Equality and Diversity lead
I want to make a change to the text at the top of the "Equality and Diversity" page
So that I can make things clearer for candidates

Please can you replace the text under the heading "Equality and Diversity" with this text. 

New version
 
The JAC is committed to equality and diversity and monitors selection processes to ensure that they are fair. If you do not want to disclose your diversity data in any given area, please select ‘Prefer not to say’ for the relevant question.

The JAC will use the information you provide in two ways: where the Equal Merit approach applies, and to monitor the selection process. Other than for the purposes of Equal Merit, your diversity monitoring information will not play any part in the selection process.

The JAC may also use the information you provided for the purpose of **“Outreach”,** to support our statutory duty to encourage diversity in the pool of applicants for judicial appointment. 

**Note:  Use this link on the word "Outreach" https://www.judicialappointments.gov.uk/diversity-strategy**

If you are recommended for an appointment we will also share your information with the Ministry of Justice, Judicial Office and Her Majesty's Courts and Tribunal Service.

You can opt out if you do not wish to share your data with MoJ, HMCTS, and Judicial Office.

**Comment by ClaireTroughtonJAC** [comment]
Link to Outreach page will be available 3/9

**Comment by lloback** [comment]
This is done.
