### ISSUE TITLE
Ability to hide an exercise from the vacancies list

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/apply#410]
As an admin
I want to be able to create an exercise but not display it to potential exercise on the vacancies list
So that I can use it as an example exercise and qualifying test for new users to try out

I need to be able to create an exercise that can run QTs but does not require someone to have applied for the exercise first to take the test.  Ideally they could understand how QTs work so they were prepared when they are asked to sit one.  

We need to be able to provide a link to a test rather than have need of an application.

**Comment by KateMJAC** [comment]
Hello @warrensearle, has this work been completed via another ticket? we have run a few QTs on the pltform now, so wondering if it had been done.

**Comment by warrensearle** [comment]
@KateMJAC we have implemented Invitation-only Exercises (admin#915) and also, perhaps more relevant, Dry Run QTs (admin#876). I suspect these cover the requirement here. If that is the case please close this ticket.
