### ISSUE TITLE
Further changes to QT - Apply

### ISSUE THREAD

**Issue by tomlovesgithub** [jac-uk/apply#414]
Following the internal testing of the QT functionality we need to complete the following work

Apply:

- [x] @tomlovesgithub  Pinning the timer to the screen - there was some feedback to say that when you scrolled down the timer disappeared. [confirmed on staging]
~~- [x] @tomlovesgithub Adding a "back" link to the countdown component, text being "previous question" or "previous" in mobile view~~ [confirmed on staging - missing the PREVIOUS on mobile view - moved #444 ]
- [x] @tomlovesgithub  Amending the test confirmation page to only link to the remaining test for that day. [Confirmed on staging]
- [ ] @tomlovesgithub Additional modal for starting test (as seen in screens) << Not on staging - My bad!
- [x] @tomlovesgithub Show truncated version of question title on overview page [Confirmed on staging]
- [x] @lloback  Preventing a candidate from taking a test more than once [confirmed on staging]
- [x] @lloback BUG. It is possible to go back in the browser and view/change answers. These are not saved to db however we should improve UX [ moved to issue #434 ] [confirmed on staging]
~~- [x] @warrensearle BUG: Timer doesn't handle duration greater than 60 minutes!~~ [ moved to #435 ] [confirmed on staging]
~~- [x] @warrensearle  Track online presence of participants as per [this example] (https://firebase.google.com/docs/firestore/solutions/presence)~~ moved to #838
- [x] @warrensearle Situational judgement. Should not be able to choose Most and Least on the same answer  [confirmed on staging]
- [x] @warrensearle BUG. Critical analysis question generates console error  [confirmed on staging]
~~- [x] Potential BUG cant reach bottom of Important Info page on iPad~~ 
- [x] @tomlovesgithub Icons on countdown component [confirmed on staging] bad position to be fixed on #444
- [x] @warrensearle Countdown component should only have 2 STATES Green and Red (5 mins or less) [confirmed on staging - not red]
- [x] @tomlovesgithub Question text covering two thirds of page width [confirmed on staging]
- [x] @tomlovesgithub "Exit" test link in countdown component [confirmed on staging]
- [x] @tomlovesgithub BUG: Footer floats over the top of the QT information page (and others). See screen grab below
![Screenshot 2020-09-10 at 17.22.41.png](https://images.zenhubusercontent.com/5e412648a39708a606c962c9/926516fb-78af-4153-ba6c-7dad4f468737) [confirmed on staging]

**Comment by warrensearle** [comment]
@lloback please can you create tickets for each of the incomplete tasks.

**Comment by warrensearle** [comment]
Hey @lloback and @tomlovesgithub looks like some of these fixes are not on staging (or production). Please check code has been pushed and merged.

The following, for example, aren't there (there may be more):
- Additional modal for starting test (as seen in screens)
- Icons on countdown component

Also looks like the styling of the Previous question and Exit test links needs refinement:
![Screenshot 2020-09-16 at 23.21.15.png](https://images.zenhubusercontent.com/5e412648a39708a606c962c9/92a85964-b831-44c9-a0e4-eab4f8c4fe0a)
