### ISSUE TITLE
QT: Scenario test - mobile

### ISSUE THREAD

**Issue by lloback** [jac-uk/apply#451]
As a candidate I want to complete a scenario test so that I can demonstrate my skills and progress my application for a new role

---

We need to build out the screens for scenario tests across mobile (Desktop version on #450).
Check #450 for Data model.

We will need a few new components / pieces of functionality including:
- Word count on a text area (the same as desktop version)
- Accordian (with scroll, perhaps?)
- Button / toolbar pinned to bottom of screen on mobile

Initial visual for mobile / small screen:
![Mobile - Scenarios view.jpg](https://images.zenhubusercontent.com/5e412648a39708a606c962c9/8a95e4e6-ddd3-43d7-a3df-9f994fb57f99)
![Mobile View scrolled.jpg](https://images.zenhubusercontent.com/5e412648a39708a606c962c9/22c66092-0902-4d73-9fea-4d51fcf8d75e)
![Mobile - Worst case view.jpg](https://images.zenhubusercontent.com/5e412648a39708a606c962c9/4e7ba9f5-0e40-4c4f-a1f4-a14afb6bee22)

**Comment by warrensearle** [comment]
@Rebecca-mcknight1991 we might not want to implement all of this. Please review.
