### ISSUE TITLE
QT Submitted page: the other QT tests showing were already completed

### ISSUE THREAD

**Issue by lloback** [jac-uk/apply#461]
https://apply-develop.judicialappointments.digital/qualifying-tests/sniPFdQlHB6AcKppqYxv/submitted
![image](https://user-images.githubusercontent.com/15261814/94001340-48664000-fd90-11ea-9da0-66ea8734c1a2.png)

The other QT tests showing were already completed.
So, maybe we can't use a future date - we need to check that the tests are due.
Should only show one test.
It leads to the following page:

![image](https://user-images.githubusercontent.com/15261814/94001502-7cd9fc00-fd90-11ea-9f0a-09ab5a3c64bf.png)

**Comment by warrensearle** [comment]
Note there is a further bug where the test being linked to is not loading correctly. This is to do with code not picking up the change in selected test.
