### ISSUE TITLE
Prevent candidates editing answers completed during previous test

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/apply#477]
We can look at the `started` and `completed` timestamps to determine if an answer was provided in a previous test.

For CA and SJ previously completed questions should be locked

For Scenarios previously completed questions should be locked

**Comment by lloback** [comment]
If the date of the start is before the start of the test, then they shouldn't change the answer.
- The form field should be disabled
- A message saying that you can't edit a previous question from another exam

**Comment by warrensearle** [comment]
I'm not sure we need `mode`, just the following logic:

if `.responses[questionIndex].started` is earlier than `.qualifyingTest.startDate` and `.responses[questionIndex].completed` then the question at `questionIndex` should be locked.

Am I missing something?

**Comment by warrensearle** [comment]
This has been implemented now in hotfix 1.20.2
