### ISSUE TITLE
QT: Auto-save function that saves the answer every 5 sec or so …

### ISSUE THREAD

**Issue by lloback** [jac-uk/apply#480]
As a candidate, 
When I am doing a QT,
I want my answers to be saved every 5 seconds,
So if I lose access to the internet I don't lose my answers

---

This will be for every type of questions, but it is more relevant to the Scenario.

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle need for 4 Nov. Not sure if we need a label for this.

**Comment by lloback** [comment]
added to Current Column
