### ISSUE TITLE
Save/Skip should return user to Review page

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/apply#491]
As a candidate 
I want to be able to quickly change my answer to a question before submitting my test
So that I can make last minute changes

---

**Expected**
When a user has reached the Review page for a test then if they follow a link to a question upon clicking Save or Skip they should return to the Review page.

**Actual**
When a user has reached the Review page for a test then if they follow a link to a question upon clicking Save or Skip they are taken to the next question.
This means user has to cycle through all the remaining questions before they can finish Review and submit their test.

**Comment by lloback** [comment]
Check if the previous router page is REVIEW - if so, go back to review, otherwise go to the next question.
