### ISSUE TITLE
Ensure user is using the latest version of our software

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/apply#493]
**NOTE: this issue was identified following a live qualifying test where some responses were submitted using our old data model, whilst most were using our newly modified data model. This indicates that some users were using a previous version of our software.**

---

With an evolving platform we should ensure our users are always using the latest version of our software.

By storing the version number in our SPAs and exposing the latest version number, perhaps via the database, we can trigger a prompt to be displayed to the user to refresh their version (refresh the browser, perhaps clearing cache)

Here's a screen grab from Miro
<img width="888" alt="Screenshot 2020-09-30 at 16 52 32" src="https://user-images.githubusercontent.com/8524401/94709259-6fe37c80-033d-11eb-91ad-3184b384619b.png">

[Add how we are going to store the version on the database - what is the data model?]

**Comment by warrensearle** [comment]
@lloback please add to this ticket any notes about setting cache-control headers, or reference the ticket which covers this.

**Comment by lloback** [comment]
Maybe we can add to the header of the files the following information: https://web.dev/http-cache/

**Comment by lloback** [comment]
For firebase hosting, we can add the header on the `firebase.json`:
https://firebase.google.com/docs/hosting/full-config#headers

**Comment by warrensearle** [comment]
Nice one @lloback lets get the headers updated
