### ISSUE TITLE
QT: timer should stop at end of the advertised endDate

### ISSUE THREAD

**Issue by lloback** [jac-uk/apply#495]
**Is your feature request related to a problem? Please describe.**
The timer should adjust to the end of the test time. If a user starts a test 5 minutes before the end of the test, the timer should be adjusted to 5 min. That way the timer will stop at exactly the time that the test should end.

**Describe the solution you'd like**
Pseudo-code
```
testDurationAdjusted = 45;  // from database duration.testDurationAdjusted
amountOfTimeUntilTestEnds = 15; // dateNow minus endDate ;
if testDurationAdjusted < amountOfTimeUntilTestEnds then testDurationAdjusted = testDurationAdjusted
if testDurationAdjusted > amountOfTimeUntilTestEnds then testDurationAdjusted = amountOfTimeUntilTestEnds
```

**Comment by Rebecca-mcknight1991** [comment]
Agreed. Good spot guys.
