### ISSUE TITLE
Candidates unable to apply for 00019

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/apply#508]
**Describe the bug**
When candidates go to apply it either won't let them save and continue or won't even let them go to the application. 

**To Reproduce**
1. Go to jac website
2. Click on district judge
3. Scroll down to check if eligible and apply, yes to UK citizenship 

**Expected behavior**
Should be able to apply. 

**Screenshots**
![Screenshot 2020-10-06 at 15.04.43.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/884e7340-3275-4786-96e2-8114999074ed)

**Additional context**

Urgent as closes tomorrow at 1pm.

**Comment by warrensearle** [comment]
This is a permissions issue, just looking into why permission is not being granted

**Comment by warrensearle** [comment]
This is fixed now. It was an issue with the way exercise open and close date had been stored. The exercise must have been set up during the time we had a bug admin#831
