### ISSUE TITLE
"comment out the "Exercises in progress" section on the "/vacancies" page"- Jeremys Request

### ISSUE THREAD

**Issue by tomlovesgithub** [jac-uk/apply#512]
![image.png](https://images.zenhubusercontent.com/5e9d7da659354ff66af12557/9162b0d0-05ea-470b-a551-d5da35365cdb)https://judicial-appointments.slack.com/archives/CLV1P6D6J/p1601924140006800

**Comment by Rebecca-mcknight1991** [comment]
@londonprojects suggest you review this
