### ISSUE TITLE
Reasonable length of service is preventing submit, candidates not alerted

### ISSUE THREAD

**Issue by tomlovesgithub** [jac-uk/apply#522]
Candidate had issue submitting application, upon inspection their application was missing an answer to the _Reasonable Length Of Service_ question which disables the submit button. 
To fix this we should add in validation for in the apply/RLOS view and review the way users are alerted to missing info on the tasklist page. 

`if (!this.application.progress.reasonableLengthOfService) { isComplete = false; }`

**Comment by warrensearle** [comment]
We need to re-factor the task list and review pages as they currently have duplicate copies of the same logic.

**Comment by mbrookeswebdev** [comment]
This bug no longer exists. There was also some work done recently to separate logic/remove duplication by introducing mixins.
