### ISSUE TITLE
Include validation on post qualification experience form

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/apply#531]
**Actual**
The candidate is able to click the 'Save and Continue' button on the Post Qualification Experience page without having entered anything into the form. On the task list / overview page 'Post Qualification Experience' is also marked as 'DONE'.
(see screen grabs below)

**Expected**
The candidate should be required to enter data into the form before they are able to 'Save and Continue'.
On the task list / overview page 'Post Qualification Experience' should only be marked as 'DONE' when the candidate has provided required data.

![Screenshot 2020-10-14 at 15.17.17.png](https://images.zenhubusercontent.com/5e412648a39708a606c962c9/b1ade07a-9bf8-49f0-a7e0-69df15fd814a)

![Screenshot 2020-10-14 at 15.32.02.png](https://images.zenhubusercontent.com/5e412648a39708a606c962c9/e8994d22-5578-4e24-aa35-b690eac93f56)

**Comment by warrensearle** [comment]
@Rebecca-mcknight1991 should the candidate be able to confirm 'I do not have any PQE' on the form, so they can continue or do we always expect candidates to have experience?

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle for legal and leadership the PQE is required. Even if they haven't done pupillage in the normal way they have to put some kind of experience lawyering. 

I think for non-legal and non-legal leadership they both say relevant membership and relevant experience but the way those are written makes me think they don't need to be required.

So just this section for legal and leadership.
