### ISSUE TITLE
Candidates need to see closed but in progress vacancies 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/apply#537]
**Is your feature request related to a problem? Please describe.**
As a candidate I am frustrated when I cannot see a vacancy I have applied for and is now closed, particularly the timeline information. 

**Describe the solution you'd like**

https://apply.judicialappointments.digital/vacancies

1. What was previously in progress applications e.g. closed but in flight needs to be re-added BUT with different headings
2. Open vacancies needs to now say 'Open for applications' 
3. In progress needs to now say 'Closed for applications' 
4. Future needs to say 'Future applications' 

**Describe alternatives you've considered**
Keeping it as it is but 1) candidates cannot see in progress anymore and 2) this language is clearer

**Comment by warrensearle** [comment]
@lloback please can you take care of this one as a hot fix?

**Comment by lloback** [comment]
yes.
