### ISSUE TITLE
Write test script for Invite-only Exercises

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/apply#557]
Add a test script for Invite-only Exercises from the Candidate perspective. See Epic admin#915 for requirements to be tested

Test scripts are stored in a Google Sheet [here](https://drive.google.com/drive/folders/142leRfwBIMZQbmZXivGzhcYrYTUfYUOS)

**Comment by lloback** [comment]
The work for this task was carried out on sprint 20OCTB.
If new work is needed we should create a new task.
I am closing this task now.
