### ISSUE TITLE
Write test scripts for Qualifying Tests

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/apply#561]
Add test scripts for each type of Qualifying Test, as follows, from the Candidate perspective. See Epic [TBC] for requirements to be tested

- [x] Test script for Critical Analysis QT
- [x] Test script for Situational Judgement QT
- [x] Test script for Scenario QT

Test scripts are stored in a Google Sheet [here](https://drive.google.com/drive/folders/142leRfwBIMZQbmZXivGzhcYrYTUfYUOS)

**Comment by lloback** [comment]
This work was carried out on the 20OCTB sprint. 
If some other works on this need to be carried out we should create another task...
