### ISSUE TITLE
Update the data model 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/apply#574]
1. Version number 
2. Improve way character data being stored

**Comment by mbrookeswebdev** [comment]
Please see [Apply 683](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/jac-uk/apply/683), [Admin 1135](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/1135) and Miro board [here](https://miro.com/app/board/o9J_lZAkLUM=/)

**Comment by warrensearle** [comment]
There is no code change as part of this ticket (see apply#683, admin#1135 instead) so moving this ticket to done
