### ISSUE TITLE
Write a test script 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/apply#576]

**Comment by mbrookeswebdev** [comment]
Added test script to [Apply document. ](https://docs.google.com/spreadsheets/d/1ui5XkroLH1UHUgahLuaVrFLQr6afIuAXo1r9cQZRgeE/edit#gid=1103835674)

**Comment by mbrookeswebdev** [comment]
Added test script to[ Admin document](https://docs.google.com/spreadsheets/d/1BAyEPjLIOQcVFfSCRTsBzDL-lKeQscuFkTAWLJelcvU/edit#gid=1950229983).

**Comment by warrensearle** [comment]
Test script looks good
