### ISSUE TITLE
Add first and last name fields to application form

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/apply#616]
In order to provide better data to Judicial Office when we collect Candidate details we are going to ask for 'First name' and 'Last name' instead of the current 'Full name' field.

**Actual**
![Screenshot 2021-02-26 at 11.31.40.png](https://images.zenhubusercontent.com/5e412648a39708a606c962c9/d56bc96d-74d1-4227-a425-1e221f50a574)

**Expected**
Replace 'Full name' with two fields instead titled 'First name' and 'Last name'

**Note**
To reduce the immediate impact of this change we will combine the data inserted into the name fields and still populate the existing `fullName` field.

**Data Model**
The following fields will be added to `applications` documents
- `firstName`
- `lastName`

In order to minimise the impact of this change we will retain the existing `fullName` field and auto-populate it with `firstName + ' ' + lastName`. With time we will prioritise displaying `firstName` and `lastName` instead of `fullName`

**Comment by warrensearle** [comment]
Here's how GDS suggest asking for this information: 
https://design-system.service.gov.uk/patterns/names/

**Comment by mbrookeswebdev** [comment]
To test -

- Please create a new candidate on Apply and apply for a vacancy. Note whether the candidate is asked to enter first/last names on the forms.
- Please check submitted Applications to see if the first/last names are displayed correctly.
- Log in as an existing candidate and apply for a vacancy.
- Please check if entered first/last names are displayed correctly for old and new submitted Applications.
- Please log into Admin and check old and new Applications - whether the first/last names are displayed where they were entered and whether it is possible to change them as required.

**Comment by KateMJAC** [comment]
Tested by user testing group with positive result. I also tested with a positive result.
