### ISSUE TITLE
Area in candidate account to access their profile information 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/apply#621]
The candidate should be able to get into their core profile information. Suggest there needs to be a purple button like with sign out and vacancies but near where it says which email they are logged in with saying 'Account' when they click account their core profile information comes up.

1. personal details
2. character information
3. equality and diversity

**Comment by KateMJAC** [comment]
To be reviewed as part of the May application and profile edit items on the RM.
