### ISSUE TITLE
Candidate should not see 'New application process' blue box 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/apply#625]
![Screenshot 2020-11-12 at 15.51.34.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/71b5aa3e-8544-45c3-9b82-8ac861048327)

The candidates should no longer see the shot above. This used to happen when they hit 'Check if you're eligible and apply'. They should not just be taken to the citizenship question below:

![Screenshot 2020-11-16 at 14.19.35.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/c1892569-2f12-4be1-b1c3-281bccd58145)

**Comment by warrensearle** [comment]
Hey @tomlovesgithub could you take care of this one. The view and route can be deleted
