### ISSUE TITLE
[Snyk] Security upgrade jspdf from 1.5.3 to 2.1.1

### ISSUE THREAD

**Issue by lloback** [jac-uk/apply#631]
**Describe the bug**
New version jspdf:

[Snyk] Security upgrade jspdf from 1.5.3 to 2.0.0

This needs some change and configuration, as the new version is compatible with the old one, and they deprecated the function that we were using to create our pdf [`fromHTML`](https://github.com/MrRio/jsPDF/releases/tag/v2.0.0) and replaced with `html`.

https://rawgit.com/MrRio/jsPDF/master/docs/module-html.html#~html

May be we should not move to this new version

**Comment by warrensearle** [comment]
Agreed. We should not upgrade at this time unless there's a clear risk to staying with the version we have, which I don't think there is.

In quieter time we need to verify whether this feature is actually used and useful for candidates

**Comment by lloback** [comment]
The decision was to keep as it is, after through investigation.
