### ISSUE TITLE
Rewording not found page

### ISSUE THREAD

**Issue by tomlovesgithub** [jac-uk/apply#643]
![image.png](https://images.zenhubusercontent.com/5e9d7da659354ff66af12557/2b0ae74d-b5c0-411c-b9fe-d685fece4720)
- Add missing apostrophe

@tomlovesgithub we like Warren's suggestion of

"Oops, the page you requested does not exist or you no longer have access to it."

**Comment by warrensearle** [comment]
@Rebecca-mcknight1991 or @joy-ade please confirm the wording you would like on this page. Perhaps something like the following?

"Oops, the page you requested does not exist or you no longer have access to it."

**Comment by Rebecca-mcknight1991** [comment]
@tomlovesgithub if clear please move from blocked :)

**Comment by Rebecca-mcknight1991** [comment]
@tomlovesgithub this can move now? Can you check you are happy then shift the ticket out of blocked.
