### ISSUE TITLE
Unable to Apply for a Open Exercises

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/apply#658]
**Describe the bug**
 We are not able to apply for open exercises. The links for more information is missing and so is the apply bottom. I have attached a screen shoot for more information.

**Expected behaviour![Apply bottom.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/d9d22c94-b645-43d5-8a9d-0956cd5b67c1)![link.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/443dda0f-5ed8-4a4b-bf25-1a9198859363)**

.

**Comment by joy-ade** [comment]
@warrensearle can you look at this pls. This error is on apply-staging.

**Comment by warrensearle** [comment]
Thanks @joy-ade, sure one of us will take a look at this today and either fix or update here with any observations.
