### ISSUE TITLE
Refactor Review.vue and TaskList.vue

### ISSUE THREAD

**Issue by mbrookeswebdev** [jac-uk/apply#688]
Both components are very large and can be difficult to work with, so it would be good to refactor, simplify and/or break into smaller parts if possible.

**Comment by HalcyonJAC** [comment]
Development Plan:

- [x] Reduce no. of lines of code where possible (without chaning any logic), just to make the files easier to browse.
  - Note: Only do this where code is not made more complex by doing so.
- [ ] Some functions appear in both components. Create a mix-in that be imported into both components (i.e. to avoid code duplication).

**Comment by HalcyonJAC** [comment]
Before:
  - TaskList: 
    - Vue template = 113 lines
    - JavaScript = 374 lines
    - CSS = 11 lines
    - Total line of code = 499
  - Review
    - Vue template = 1874 lines
    - JavaScript = 263 lines
    - CSS = 12 lines
    - Total line of code = 2149
After:
  - TaskList = 
  - Review = 
  - ApplyMixIn =

**Comment by KateMJAC** [comment]
This has been sent to the UTG, awaiting feedback.
