### ISSUE TITLE
Amendments to Character Form Enhancement

### ISSUE THREAD

**Issue by KateMJAC** [jac-uk/apply#698]
As the Head of Secretariat I have some amendments that I would like applied to the recently created character form within candidate applications. These are: 

1)	Q1 and Q2 to switch positions. 
2)	Q4 Details should read as follows: Please add details of your disqualification here including the dates of your disqualification period.
3)	Q5 & Q6 to be removed. 
4)	On the financial questions have one information point displayed at the top of the page to cover all questions. 
5)	Q13 to Q20 remove the word offence so it just says Date and remove the Day box so candidates are only required to include month and year. 
6)	In paragraph 1 of the declaration replace Selection Exercise Team with Judicial Appointments Commission.
7)	In paragraph 3 remove the word also, so instead it reads I understand…

**Comment by mbrookeswebdev** [comment]
I've updated test scripts for Character Information - [Apply script] (https://docs.google.com/spreadsheets/d/1ui5XkroLH1UHUgahLuaVrFLQr6afIuAXo1r9cQZRgeE/edit#gid=1103835674) / [Admin script](https://docs.google.com/spreadsheets/d/1BAyEPjLIOQcVFfSCRTsBzDL-lKeQscuFkTAWLJelcvU/edit#gid=1950229983)
