### ISSUE TITLE
Adding word limits to ASC response fields on the platform

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/apply#706]
**The issue**

As an admin, I have to manually check whether answers provided in relation to Additional Selection Criteria are within the 250-word limit that always applies to this question. This task takes members of my team a very long time to complete, especially when we have large exercises with over 400 candidates. User error can also occur when the text is copied out of the platform and pasted into Word to check, leading to a lack of accuracy. 

**Describe what solution you would like**

I would like functionality that automatically applies a 250-word limit to the answer field for Additional Selection Criteria questions. 
This will ensure that word limit requirements are applied fairly for all candidates while reducing drain on Selection Exercise Team resources.

If users are able to include bullet points or numbering that is not included in the word count, that is ideal. 

**Describe alternatives you have considered**

Current state - manual checking of application form answers, which is too resource intensive. 

![Word Count.png](https://images.zenhubusercontent.com/5fcfacf3d4e677f3af4fdecb/b46b4d6e-752b-4fa0-84db-e6268069fd4d)**The issue**

**Comment by tomlovesgithub** [comment]
ive just had a once over of the scenario word limit logic and what ive written for this solution works quite differently, but a notable differing requirement is removing hyphens so i think for now it may be best to leave them separate although same of the logic could eventually go to JAC-kit for sharing/future refactoring

**Comment by warrensearle** [comment]
Hey @KateMJAC and @tomlovesgithub there are other places in the code base that ask the 'Additional Selection Criteria' questions, as follows:
- Self Assessment Competencies
- Statement of Eligibility
- Statement of Suitability

This change will need rolling out to all those places. 

In addition there's a little too much duplication so, unless there are subtle differences I haven't spotted, I'd suggest we refactor slightly so we re-use one piece of code for ASC questions. @tomlovesgithub you know what to do :)

**Comment by HalcyonJAC** [comment]
I have checked the repo and can't see a #706 (or #705) feature branch to pull down locally and review:

![image.png](https://images.zenhubusercontent.com/603e1836d75b05b4fc7c9c59/7d955dd2-68c8-4618-ae35-a7972551658e)

**Comment by KateMJAC** [comment]
A test script for this feature has been circulated to the user testing group. Responses/feedback should be provided in the uer testing Slack channel by COB 1 April. 

This feature needs to be pushed to production when there are no exercises open. It looks like we have 14 April as our next oportunity to push this to production.

**Comment by KateMJAC** [comment]
Due to the pre QT code freeze, this ticket cannot be released until after 27 April. At that stage we will need to assess when an apprioriate window will be for release, taking into account what, if any exercises are open for applications.

**Comment by KateMJAC** [comment]
As of today, we only have 00064 open on production. 

Tom has been asked to confirm whether releasing this on production would negatively impact that open exercise.

**Comment by KateMJAC** [comment]
If this ticket is released while 00064 or any exercise with ASC is open will not see the changes implemented for apps in draft. This ticket needs to be released when no exercises are open or when no open exercises have ASC. 

We will continue to code review and send to the UTG so that we can push the button when ready.
