### ISSUE TITLE
Candidate Unable to Enter Email Address with Apostrophe

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/apply#713]
Candidate is unable to enter the email address for her independent assessor as it has an apostrophe in this (this is is correct email address). The Selection Exercise Team has replicate the issue and it does the same to me.![Capture.PNG19.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/0e527146-d74b-4e60-9242-667639e20bfb)

**Comment by KateMJAC** [comment]
As assessor's email addresses can be edited at any time, including after the application window has closed, this ticket is not urgent. 

The issue needs resolving in advance of the SET sending out IA requests on 11 June 2021.

**Comment by KateMJAC** [comment]
The exercise team has confirmed that they are willing to deal with this assessor manualy and not send them an automated IA form through the platform . 

This ticket can be placed in 2000-2021 for completion at a future date.

**Comment by tomlovesgithub** [comment]
*Note* this work has been placed in draft so email validation can be centralised or consistently updated

**Comment by andrew-isaac** [comment]
@tomlovesgithub  is this ready for testing, complete of blocked?
