### ISSUE TITLE
Prevent QT countdown from hiding QT information.

### ISSUE THREAD

**Issue by tomlovesgithub** [jac-uk/apply#718]
Testing has revealed an issue with the QT timer.
Due to ongoing changes to the format and display of QT info and questions, it is likely that candidates will split their display to see both the reading materials and questions at the same time. 
We must ensure the timer doesn't cover any text or information on any device at any width.

![image.png](https://images.zenhubusercontent.com/5e9d7da659354ff66af12557/7a323cd2-b975-4a88-8199-5dc337f36543)

**Comment by KateMJAC** [comment]
Hello @tomlovesgithub I have tested this and I was able to resize/split page and ensure countdown bar does not cover the any text. 

At all window sizes all of the text was clear of the countdown bar, even when I need to scroll to see the bottom of the text at certain window sizes. 

Nice work!

I have three additional staff testing this tomorrow morning at 8:30. We are unable to push this to live without several people testing it. 

Can you please clarify whether this ticket can be pushed to production if the numerous other tickets in the pipeline cannot be released?

**Comment by KateMJAC** [comment]
@tomlovesgithub as discussed earlier this morning this work has now also been tested by three SET members and they have confirmed that everything included in your testing script worked as described. 

We can now push this to production. This will need to be completed before COB Friday. Please liaise with Warren to confirm whether this can independently released apart.

**Comment by KateMJAC** [comment]
Update: This has been tested and can go to production after the 051 mop up on 1 April 2021.
