### ISSUE TITLE
Fullscreen modal box on mobile

### ISSUE THREAD

**Issue by tomlovesgithub** [jac-uk/apply#723]
![Screenshot 2021-03-16 at 18.22.40.png](https://images.zenhubusercontent.com/5e9d7da659354ff66af12557/93695db3-a410-4753-90ea-20bf23c5f6cf)![Screenshot 2021-03-15 at 15.19.31.png](https://images.zenhubusercontent.com/5e9d7da659354ff66af12557/4d9862ec-15a2-41e5-ad84-6347f1d281fb)

**Comment by KateMJAC** [comment]
Hello @tomlovesgithub I have tested this on my mobile and I could only see: 

- The time/numbers displayed. I no longer saw ‘Time remaining’.
- 'Previous'. I could not see the 'Question' of 'Previous Quesiton'.
- The 'Are you sure?' box covering the whole screen when exiting the test.  

Again, nice work! I'm happy that that this can go live on production, pending further testing by other staff. 

I have three additional staff testing this tomorrow morning at 8:30. We are unable to push this to live without several people testing it. 

Can you please clarify whether this ticket can be pushed to production if the numerous other tickets in the pipeline cannot be released?

**Comment by KateMJAC** [comment]
@tomlovesgithub as discussed earlier this morning this work has now also been tested by two SET members and they have confirmed that everything included in your testing script worked as described. 

We can now push this to production. This will need to be completed before COB Friday. Please liaise with Warren to confirm whether this can independently released apart.

**Comment by KateMJAC** [comment]
Update: This has been tested and can go to production after the 051 mop up on 1 April 2021.
