### ISSUE TITLE
Qualifying test reset not working correctly

### ISSUE THREAD

**Issue by tomlovesgithub** [jac-uk/apply#730]
There is some bugginess/uncovered edge cases within the reseting of QT's.

I have observed that a when a test is completed, if DNF(out of time), or submitted, reset functionality is doesn't function correctly, tests are reset and appear in the open tests tab, but cannot be started, until the started and completed fields in the status log have been null'd.

However when the QT has not been finished (candidate have exited or closed QT) reset can be achieved.

Upon further investigation, the issue is regarding a number of checks which happen before displaying the information page.

Once a QT response has been reset, the `status`  field is set to `activated`. The status log remains, including a `start time`, `finish time` and `duration`.

```
{
   status: activated,
   statusLog: {
      started: DATE,
      completed: DATE,
   }
}
```

The checks which were causing the apply side app to fail to grant access to the QT were:
```
apply > QualifiyingTest.vue 
...
        if (noTimeLeft || isCompleted ) {
          return this.redirectToList();
        }
...
```
There are a few issues here, and the logic in general could do with some consolidation.
`noTimeLeft` is based off of a locally computed value `isTimeLeft` which is calling a getter on the `qualifyingTestResponse` store which utilises a helper function `helperTimeLeft`. 

**`helperTimeLeft` is not exclusively checking time left** it also included a few checks of the status log, including checking if there was a `completed` entry, which is what the `isCompleted` check at the 'top' level of this is also doing. 
This is the first point at which the current reset is rejected.

`helperTimeLeft` also includes a check for an `endTime` variable which it calculates based off of the existence of a startedTime in the statusLog, plus duration and adjustment.
```
    const startTime = obj.statusLog && obj.statusLog.started;
...
    const endTime = new Date(startTime.getTime() + duration * minute);
    if (endTime < Date.now()) {
      return 0;
    }
```
This means that equally the `statusLog.started` is preventing reset tests from being re-sat without the statuslogs being cleared.

Slightly less complicated, `isNotCompleted` is simply checking the status logs completed field 

```
    isNotCompleted() {
      return this.qualifyingTestResponse.statusLog.completed === null ||
        this.qualifyingTestResponse.statusLog.completed === undefined;
    },
```

These checks, both independently and together are preventing the test from being restarted apply side.

My proposed solution is to add a `reset` field to the `statusLog` when reseting **admin side.** see https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/1226

```
{
   status: activated,
   statusLog: {
      started: DATE,
      completed: DATE,
      reset: DATE,
   }
}
```

**Apply side**

I plan to remove the checks for `completed` in the `noTimeLeft` check and Insert a check for the `reset` field which would circumvent the checks which calculate the `endTime` based off of the `started` log.

in `qualifyingTest.vue` i am going to insert an additional computed field which checks for a `reset` value in `statusLog` which can then be added to the top level check which was preventing a retry/restart.

```
        if ((noTimeLeft) || (isCompleted && notReset)) {
          return this.redirectToList();
        }
```

**Comment by KateMJAC** [comment]
Based on discussions at 2/7/21 stand-up this ticket is to be progressed.
