### ISSUE TITLE
Additional dates field for candidates who select ‘I did not complete pupillage’ 

### ISSUE THREAD

**Issue by KateMJAC** [jac-uk/apply#747]
**Is your feature request related to a problem? Please describe.**

As an admin user, I’m frustrated when a candidate selects the box under the question ‘I did not complete pupillage’, because there is no option for them to then add any details about how they became a barrister. 

I then have to go back to them at a later stage to request this information. 

**Describe the solution you'd like**

When a candidate selects ‘I did not complete pupillage’ under the ‘Qualifications’ section on apply there needs to be a following supplementary question with a date box underneath:  

 ‘If you did not complete pupillage, when were you called to the Bar?’

[DATE FIELDS]

**Additional context**

Please see the picture below for more details:

![Called to the bar.png](https://images.zenhubusercontent.com/5fcfacf3d4e677f3af4fdecb/3a2cd165-32ae-4140-8ed8-1a38df33a7c6)

**Comment by KateMJAC** [comment]
Whoever pics this up, if there is work on Admin associated with this ticket, please create the ticket and complete the work :)

**Comment by mbrookeswebdev** [comment]
@Kate @joy-ade  I guess this ticket came up because the Qualifications page was broken before which was fixed in [ticket 729](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/jac-uk/apply/729).

**Comment by joy-ade** [comment]
@Brookes, ***@***.***>I guess this ticket can be close now.

**Comment by mbrookeswebdev** [comment]
@KateMJAC  @joy-ade I think the work in #729 needs to be reviewed in preview url and see how/whether this ticket is needed or if it is how it should be changed.

**Comment by KateMJAC** [comment]
Gone out to UTG, update to follow.

**Comment by KateMJAC** [comment]
@tomlovesgithub we currently have two legal exercises open for applications. Releasing this ticket will impact those exercises. 

Please provide advice on what the next best steps are. Can we code around this or do we have to wait for a window where there are no legal exercises open? 

For your info @joy-ade

**Comment by KateMJAC** [comment]
This has been sent to UTG on 30/06/21 after final changes made by Tom. Will await feedback before final approval. 

Also before this ticket is released consideration needs to be given to how it may/may not impact open exercises.

**Comment by KateMJAC** [comment]
All required changes at this point made by Tom. 

Sent to the UTG w/c 2th June with no feedback due to sign-in issues. 

Sent to w/c 5 July testers

**Comment by KateMJAC** [comment]
Can't merge at present due to conflicts.
