### ISSUE TITLE
Candidate view to EMZ Test 

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/apply#748]
As a candidate l want to see EMZ test appear underneath Qualifying Test tab when l log into my account so that l view the status, title and start date/time for my online test 

Note: Candidate should be able to view the test when they log into their account.
Once allocated to the test candidates will need to be able to see the ‘title’, ‘status’ and ‘start date’/time of the test in the ‘Online tests’ section of their profile.

![Capture.PNG23.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/b9e2e1d6-f9fb-489c-8127-3f11c06c813a)

 @Darrel as mentioned l can confirm the requirement is a small  change, can you rename the qualifying Tab to online Tests 

![Capture.PNG 22.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/e58a8a55-33c0-418d-85a5-e188baf023eb)

**Comment by HalcyonJAC** [comment]
@KateMJAC

I am putting this on here so I don't forget...

@joy-ade has indicated (in the screenshot above) that there should be an extra menu item for tie-breakers in the Apply portal. During our meeting yesterday (Kate) you mentioned that perhaps it would be better to rename the _Qualifying Tests_ menu item to _Online Tests_ and have QTs and TBs appear on the same _Online Tests_ page, but you said you wanted to run that by the JAC team first.

Darrel

**Comment by joy-ade** [comment]
@HalcyonJAC Darrel having spoken warren I am  content with @KateMJAC suggestion rename the qualifying test to Online Tests. Kate will give confirmation once she has ran it by JAC team. @KateMJAC do you want me to take this requirement to the design group?

**Comment by joy-ade** [comment]
@HalcyonJAC the ticket has been updated.

**Comment by HalcyonJAC** [comment]
@joy-ade thank you :)
