### ISSUE TITLE
Timeline should not display events where they do not have a date

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/apply#750]
The timeline appears to include events even if they don't have date information.

**Actual**
Events are included on the timeline even if there's no date.
![Screenshot 2021-04-12 at 17.40.11.png](https://images.zenhubusercontent.com/5e412648a39708a606c962c9/1c4b5728-5869-4ccb-bbca-130b73105e19)

**Expected**
Events should not be included on the timeline if there's not sufficient data.

**Note**
We should also correct the data for the pictured exercise

**Comment by mbrookeswebdev** [comment]
@KateMJAC @joy-ade this ticket seems to cover the general requirements for events rather than specific events related to the timeline. I understand from Tom that it was requested to remove the name blind sift and telephone assessment from the timeline for all exercises, can you please update this ticket appropriately to enable code review/testing to be done correctly.

**Comment by joy-ade** [comment]
@mbrookeswebdev l can confirm that name-blind sift should not be displayed on the exercise timeline on the Apply side. Also the telephone assessment should not be displayed on the timeline on the Apply side.

**Comment by andrew-isaac** [comment]
Reopened ticket as there is some issues with this and what a user and candidate experience!

As a user running an exercise around 95% of paper sift exercises are name blind - This is only a few where this is not the case. When a user sets up an exercise they select the "Name Blind Sift" option and input their dates onto a timeline.

The correct order for the timeline of events of a name blind paper sift is:

- Open for applications

- Close for applications

- JAC contacts IAs

- Return date for IAs

- Name blind sift

![image.png](https://images.zenhubusercontent.com/61df018d45c3e70202f990c8/8bf415a5-2069-4867-b625-fa64ca8986e3)

When this is displayed n the apply side to a candidate it is displayed in the incorrect order with the Name Blind Sift date missing. The list should follow the same order as above and where it has "Name Blind Sift" it should display the month and year for the candidate

![image.png](https://images.zenhubusercontent.com/61df018d45c3e70202f990c8/b733d538-2487-4131-9be0-ea067bba0609)
o
