### ISSUE TITLE
Update nationality requirements

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/apply#765]
As a candidate l want to click on a tick box at the start of my application so that l can confirm I meet the eligibility criteria for the exercise.

Note A tick box should be created that will allow candidate to confirm they meet the eligibility criteria that is set out for the exercises.

A tick box for candidates to confirm that they meet the eligibility criteria for the exercise.

Eligibility
To be considered for appointment you must meet the eligibility requirements for this post.

![Capture.PNG 26.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/2e4705d1-22fe-4c16-b22a-5ae31eba42ed)

These are the new requirement
![Capture.PNG 26.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/b4c9a96b-9283-4877-931d-d3ce7fbeb958)![Capture.PNG 27.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/5fe2004f-c87a-417d-b67c-f2de3d2aa29e)![Capture.PNG28.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/f0eb99ef-0b79-43c1-9d8e-bd0f2c22c29a)![Capture.PNG 29.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/0e8b4f2c-c9b6-4891-8aeb-5d546f120446)[https://app.zenhub.com/files/201935567/7a16f6ec-6f3d-4b9f-822c-9226e6ac0d55/download](https://app.zenhub.com/files/201935567/7a16f6ec-6f3d-4b9f-822c-9226e6ac0d55/download)

**Comment by mbrookeswebdev** [comment]
@joy-ade Can you please confirm the text for the check box? Should it be something like below?

![Eligibility.png](https://images.zenhubusercontent.com/5f719a59e2ae0739a5c9b6e0/123b420e-e49d-4e76-969d-e7ff58994e43)

Also, just to confirm nothing needs to change on the following application page:

![Eligibility2.png](https://images.zenhubusercontent.com/5f719a59e2ae0739a5c9b6e0/b871e235-1bfc-46b3-865c-eb3ff92a9fdc)

**Comment by joy-ade** [comment]
@Maria this ticket is currently blocked a meeting that been planned for the 12th of May to clarify what the requirement will be for this ticket.

**Comment by joy-ade** [comment]
@mbrookeswebdev the requirement for the ticket has changed, we need to focus the questions on the nationality requirements rather than eligibility. We need to changes to the wordings.

**Comment by KateMJAC** [comment]
Confirmed by Matt that this is no longer required.

**Comment by mbrookeswebdev** [comment]
The new requirements as per screenshots below:
![1.png](https://images.zenhubusercontent.com/5f719a59e2ae0739a5c9b6e0/cbb37036-a350-4763-9ee4-16d1d1b99045)
![2.png](https://images.zenhubusercontent.com/5f719a59e2ae0739a5c9b6e0/5700d945-311b-4a5c-adf5-7483f63bc83d)
