### ISSUE TITLE
Vulnerability - npm audit

### ISSUE THREAD

**Issue by JeremykJAC** [jac-uk/apply#770]

**Comment by HalcyonJAC** [comment]
`npm audit` returns the following:

found 229 vulnerabilities (105 low, 93 moderate, 31 high) in 2422 scanned packages

Automatically fixing these vulnerabilities leave 16 unfixed.

```
fixed 3524 of 3540 vulnerabilities in 2422 scanned packages
  7 vulnerabilities required manual review and could not be updated
  2 package updates for 9 vulnerabilities involved breaking changes
```

**Comment by lloback** [comment]
@joy-ade and @KateMJAC , you also need to tick the PR for this issue so it can be merged.
