### ISSUE TITLE
Update the Character Check consent form

### ISSUE THREAD

**Issue by mbrookeswebdev** [jac-uk/apply#773]
Update the Character check consent form to reflect changes made to accommodate JO Handover transfer - i.e. addition of title, first/last name, links to the website and validation of fields.

**Comment by mbrookeswebdev** [comment]
The form has been updated as per request of the Secretariat to accommodate the following changes (please see the attached document):

- Page 1: platform form to replicate word document content. Some content has been removed and some added. 

- Page 2: guidance test for name fields to be added. 

- Page 5: ensure the HMRC details page include the fields displayed on the word doc. Yes and no fields to appear. If yes is selected a field should appear for data entry. There should be an option to provide another number. 

- Page 6: ensure the content in the word doc is replicated on the platform when a candidate is a member of a professional body.

- Page 8: platform form on ‘Declaration’ page to now reflect text in word document. Please note the page title name to ‘Consent’. 

- Page 9: platform form text to replicate text in word document. Some text has been removed. 

- Remove from current platform form: Further information to disclose (optional) page / content. 

[https://app.zenhub.com/files/201935567/36fa480f-cb93-4855-9c56-5b961399edab/download](https://app.zenhub.com/files/201935567/36fa480f-cb93-4855-9c56-5b961399edab/download)

Additionally, the HMRC text on the Consent page updated to show conditionally, depending on the Admin setting.

**Comment by mbrookeswebdev** [comment]
Emailed the pages to the Secretariat on the 10/08/21 to confirm no further changes are needed - awaiting response.

**Comment by KateMJAC** [comment]
Posted on the UTG channel today after some changes were made.
