### ISSUE TITLE
Ensure new candidates are created with a time stamped document

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/apply#776]
When a new candidate signs up a database document should be created in the `candidates` collection. It is important to ensure that this document contains content such as the `created` timestamp.

It was observed in [admin#1278](/jac-uk/admin/issues/1278) that candidate documents have been created in the past without a candidate document. The task here is therefore to:

- [x] Ensure new candidate sign up results in a new document in the `candidates` collection, populated with the `created` timestamp
- [x] Update all existing candidates to ensure their candidate document exists and contains the `created` timestamp

**Comment by warrensearle** [comment]
The Apply sign up flow has already been fixed so a new document is added to the `candidates` collection when a new candidate signs up.

There were 171 candidates (in production) without a valid `candidates` document so those documents have now been created.

The candidate search index has been refreshed and there are now 7523 searchable records.

**Comment by warrensearle** [comment]
@joy-ade  there are no code changes here but please test (in production and/or staging) that:

- [ ] When a new candidate signs up they are searchable in Admin > Candidates
- [ ] Previously 'missing' candidates are now searchable in Admin > Candidates and Admin > Applied

**Comment by KateMJAC** [comment]
@warrensearle do you have a list of 'missing' candidates that I can use to search/ask the UTG to search please?

**Comment by warrensearle** [comment]
@KateMJAC I'll send you an example candidate :)
