### ISSUE TITLE
Support having an application process

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/apply#798]
Here we are updating the application form to collect further information when it is relevant according to the defined application process

We need to ensure that the parts of the application process can be edited when, and only when, relevant.

- [x] Personal details
- [ ] Character information
- [x] Equality and diversity
- [x] Set part-time working preferences
- [x] Location preferences
- [x] Jurisdiction preferences
- [x] Additional preferences
- [x] Welsh posts
- [x] Relevant qualifications
- [x] Relevant memberships
- [x] Post-qualification work experience
- [x] Judicial experience
- [x] Relevant experience
- [x] Gaps in employment
- [x] Reasonable length of service
- [x] Independent assessors' details
- [x] Leadership Judge details
- [x] Statement of suitability
- [x] Covering letter
- [x] Curriculum vitae (CV)
- [x] Statement of eligibility
- [x] Self assessment with competencies
- [x] Additional Information

**Comment by KateMJAC** [comment]
Sent to UTG W/C 5 July. Awaiting feedback. Will update when received.

**Comment by warrensearle** [comment]
There is a bug with **Apply for this role** page not showing the full list of tasks for existing vacancies.
