### ISSUE TITLE
Dummy Live Application

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/apply#935]
As a admin I need confidence that when an exercise is launched and live on the platform all candidates are able to apply and that all information is showing, can be completed and submitted.

To do this currently I complete a fully application on Apply and submit it. I then go to the application on admin and check all the information pulls through correctly. Once I am satisfied with this I then move the application back to draft.

There are instances where admin has forgot to do this which has cause issues and for the information to be included in reporting.

If there was a way to completion the action using a .digital account and for it to not be counted in any of the date, that would be suitable.

https://admin.judicialappointments.digital/exercise/iC1xW2lXVzjdFwerP0C0/applications/draft/application/5VLunSfzT95eQXiYoPn8

![image.png](https://images.zenhubusercontent.com/61df018d45c3e70202f990c8/b88e445f-58fe-48a2-bd06-45e07d5386b1)

**Comment by warrensearle** [comment]
For now we will automatically move any application from '@judicialappointments.digital' to have a status of draft.

We need to discuss this further to see what support is needed for testing post-application processes.

**Comment by nickaddy** [comment]
@warrensearle Can we make improvements to dummy data on staging and apply and, e.g. allow staff to create full applicaitons which are not counted in the stats?

**Comment by warrensearle** [comment]
> @warrensearle Can we make improvements to dummy data on staging and apply and, e.g. allow staff to create full applicaitons which are not counted in the stats?

@nickaddy yes we can. Right now @HalcyonJAC has coded this so that any applications created by candidates with email addresses ending @judicialappointments.digital are moved to Draft. This means they are kept out of the application process and stats. If we want these applications to go further in the process, e.g. take part in online tests, sift, IAs - then we can work out and agree a solid way to support this.
