### ISSUE TITLE
Produce a list of required and optional fields

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/apply#955]
Something to fix: we need to review which fields are required or optional and update the code accordingly

[List of required fields](https://docs.google.com/spreadsheets/d/1kBiPTinKe-YtbzseZTpaC73iHh3-oS_4Aicv_xnHYxg/edit
)

**Comment by tomlovesgithub** [comment]
[List of required fields](https://docs.google.com/spreadsheets/d/1kBiPTinKe-YtbzseZTpaC73iHh3-oS_4Aicv_xnHYxg/edit)

**Comment by warrensearle** [comment]
This completes the first stage of work to review our required and optional fields - we have provided a list of all fields. 

Once the list has been reviewed any changes will be written as new issues therefore we can close this issue as completed.
