### ISSUE TITLE
Enable candidates to apply for a vacancy in Welsh

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/apply#961]
This ticket is part of jac-uk/admin#1778 where "all exercises which have a welsh post should offer the candidate the opportunity to complete an application in Welsh"

---

Here we are rolling out the designed solution (see jac-uk/admin#1778)

**Key tasks**
 - [x] Include a way for a candidate to opt to complete their application in Welsh
 - [x] Replace all English text with agreed placeholders using solution 3 proposed in #962
 - [x] Ensure the submitted application is marked as having been completed using the Welsh version of the application form

**Comment by andrew-isaac** [comment]
[https://app.zenhub.com/files/201935567/a46ad9fb-11ab-41e5-abee-c20575758538/download](https://app.zenhub.com/files/201935567/a46ad9fb-11ab-41e5-abee-c20575758538/download)

Attached is the Welsh Translation returned @HalcyonJAC and @warrensearle
