### ISSUE TITLE
A pattern for switching between English and Welsh language

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/apply#962]
This ticket is part of jac-uk/admin#1778 where "all exercises which have a welsh post should offer the candidate the opportunity to complete an application in Welsh"

### Problem
In our code base we have English text coded in a number of places. These can be grouped as follows:

**Plain text**
```
<h1>This is a page title</h1>
```

**HTML**
```
<p>This is all content, including an inline <a href>link</a> and some <strong>styling</strong></p>
```

**Props**
```
<component label="some text goes here" />
```

**Computed/filtered values**
```
<label>{{ type | lookup }}</label>
```

### Solution

Our solution should provide an efficient and reliable way for all English text to be interchangeable with Welsh.

#### Option 1: Use plugin vue-i18n
Here we will use the [Vue i18n](https://kazupon.github.io/vue-i18n/) plugin.
See the plugin for full details but essentially this introduces a top level function we call from our vue templates and code:
```
<p>{{ $t("message.hello") }}</p>
```

Data is stored in json files as follows:
```
{
  en: {
    message: {
      hello: 'This is the text'
    }
  },
  cym: {
    message: {
      hello: 'This is the text in Welsh'
    }
  }
}
```

**Benefits:**
 - Off-the-shelf solution. We are not re-inventing the wheel

**Drawbacks:**
 - We would need to think of names for all the places in our code where we have text (e.g. `persoanlDetails.pageTitle`, `personalDetails.form.title` etc)
 - How well would this support computed/filtered values?
 - This solution is built for multi-languages. We only need to support two. So potential over-kill?

#### Option 2: Write our own simple plugin
Our needs are pretty straightforward and a lightwieght top-level plugin could easily be written to do exactly what we require. Here's a [tutorial for writing a plugin](https://v2.vuejs.org/v2/guide/plugins.html).

For example we could have a top-level `function` and a `filter` used as follows:
```
<p>{{ $translate("This is the text") }}</p>
```
```
<p>{{ "This is the text" | translate }}</p>
```

Data is stored in json files as follows:
```
{
  "This is the text": "This is the text in Welsh"
}
```
or
```
[
  { 
    en: 'This is the text',
    cym: 'This is the text in Welsh'
  },
]
```

**Benefits**
 - We have full control to build exactly what we need - e.g. we could use inline text rather than needing to define placeholders, which would save time
 - Lightweight. Estimate around 15 lines of code to achieve what we need
 - We can support computed/filtered values

**Drawbacks**
 - Are we un-necessarily re-inventing the wheel?

#### Option 3: Navigate the DOM and update all text nodes
This would bypass the need to amend our code and function similar to google translate widget which does the following:
 - Navigate the DOM of the current page
 - For each text node translate the text into Welsh (in our case)
 - Update the text node with the translated Welsh text

Data is stored in json files (similar to option 2):
```
{
  "This is the text": "This is the text in Welsh"
}
```
**Benefits**
 - Quick to implement
 - Low impact as existing code does not need to be changed

**Drawbacks**
 - There could be a timing issue where user will briefly see english text before it is replaced with welsh... but this is unlikely and the only drawback I could think of

**Comment by warrensearle** [comment]
Closing as this task is done.
We went with option 3 :smile:
